import { LanguageRoadmap, TopicLevel } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
type Spec = [string, string, string, TopicLevel, string[], string, string?];
const make = ([id, title, summary, level, focus, exercise, prerequisite]: Spec) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode: 'void main() {\n  final lessons = <String>["Offline"];\n  print(lessons.length);\n}', expectedResult: `A small offline Dart or Flutter example demonstrates ${title.toLowerCase()} with a visible result.`, challenge: `Add an edge case related to ${title.toLowerCase()} and keep the UI or output predictable.`, references: ['Dart language', 'Flutter concepts', ...focus], quizQuestion: `What is the main idea behind ${title}?`, quizAnswer: `It gives ${title.toLowerCase()} a clear, testable structure.`, quizOptions: [`It gives ${title.toLowerCase()} a clear, testable structure.`, 'It only changes platform icons.', 'It makes testing unnecessary.'], quizExplanation: 'Good Dart and Flutter code keeps data flow, lifecycle, and failure behavior visible.', prerequisites: prerequisite ? [prerequisite] : undefined });
const basic: Spec[] = [
 ['dart-overview', 'Dart Overview and Toolchain', 'Understand Dart syntax, the VM, and how Flutter uses Dart.', 'Beginner', ['Dart', 'VM', 'Flutter relationship'], 'Run a small Dart program without a network dependency.'],
 ['dart-setup', 'Dart and Flutter Setup', 'Learn SDK, editor, emulator, and project concepts without depending on a remote service.', 'Beginner', ['SDK', 'Project setup', 'Tooling'], 'Create a local Flutter project outline.'],
 ['dart-variables', 'Variables, final, and const', 'Choose mutable, final, and compile-time constant values deliberately.', 'Beginner', ['var', 'final', 'const'], 'Model immutable task configuration.'],
 ['dart-types-null-safety', 'Types and Null Safety', 'Use Dart types and sound null safety to prevent absent-value mistakes.', 'Beginner', ['Types', 'Nullable types', 'Promotion'], 'Render an optional task note safely.'],
 ['dart-operators-conditions', 'Operators and Conditions', 'Build expressions and branches that handle task state clearly.', 'Beginner', ['Operators', 'if', 'Boolean logic'], 'Choose a label from a task status.'],
 ['dart-loops-functions', 'Loops and Functions', 'Repeat work and package logic into named functions.', 'Beginner', ['Loops', 'Functions', 'Returns'], 'Calculate task completion with a helper function.'],
 ['dart-collections', 'Collections: Lists, Sets, and Maps', 'Choose collection structures for ordered, unique, and keyed data.', 'Beginner', ['Lists', 'Sets', 'Maps'], 'Remove duplicate task tags.'],
 ['dart-classes-constructors', 'Classes and Constructors', 'Model application data with constructors and clear fields.', 'Beginner', ['Classes', 'Constructors', 'Fields'], 'Create a validated task class.'],
];
const intermediate: Spec[] = [
 ['dart-named-parameters', 'Named and Optional Parameters', 'Make Dart APIs readable and configure defaults safely.', 'Intermediate', ['Named parameters', 'Defaults', 'API design'], 'Build a task card constructor with optional labels.', 'dartflutter-dart-loops-functions'],
 ['dart-generics-enums', 'Generics and Enums', 'Preserve types in reusable code and represent finite states.', 'Intermediate', ['Generics', 'Enums', 'State'], 'Create a typed task result model.', 'dartflutter-dart-types-null-safety'],
 ['dart-mixins-extensions', 'Mixins and Extensions', 'Reuse focused behavior while keeping classes understandable.', 'Intermediate', ['Mixins', 'Extensions', 'Reuse'], 'Add a filter extension to a task list.'],
 ['dart-exceptions', 'Exceptions and Validation', 'Handle malformed input with useful errors and validation boundaries.', 'Intermediate', ['Exceptions', 'Validation', 'Errors'], 'Validate a task form command.', 'dartflutter-dart-classes-constructors'],
 ['dart-async-futures', 'Async/Await and Futures', 'Represent asynchronous work and update callers predictably.', 'Intermediate', ['Future', 'async', 'await'], 'Load a local fixture asynchronously.'],
 ['dart-streams', 'Streams and Event Flow', 'Process sequences of values and understand subscription lifecycle.', 'Intermediate', ['Streams', 'Subscriptions', 'Events'], 'Stream task progress updates.', 'dartflutter-dart-async-futures'],
 ['dart-json-packages-testing', 'JSON, pub Packages, and Testing Basics', 'Decode structured data, organize dependencies, and test pure Dart logic.', 'Intermediate', ['JSON', 'pub', 'Tests'], 'Parse and test an offline task fixture.', 'dartflutter-dart-exceptions'],
 ['flutter-architecture-widgets', 'Flutter Architecture and Widget Tree', 'Understand declarative UI, widget composition, and the build pipeline.', 'Intermediate', ['Widgets', 'Tree', 'Build'], 'Sketch a task screen as a widget tree.'],
 ['flutter-stateless-stateful', 'StatelessWidget and StatefulWidget', 'Choose local state ownership and rebuild only the needed subtree.', 'Intermediate', ['StatelessWidget', 'StatefulWidget', 'State'], 'Build a task toggle widget.', 'dartflutter-flutter-architecture-widgets'],
 ['flutter-context-material', 'BuildContext and Material Widgets', 'Use context deliberately and compose common Material controls.', 'Intermediate', ['BuildContext', 'Material', 'Theme'], 'Build a small task detail view.', 'dartflutter-flutter-stateless-stateful'],
 ['flutter-layout-lists-forms', 'Layout, Lists, and Forms', 'Compose Row, Column, Container, ListView, TextField, and validation.', 'Intermediate', ['Layout', 'ListView', 'Forms'], 'Build an offline task form.', 'dartflutter-flutter-stateless-stateful'],
 ['flutter-navigation-assets-themes', 'Navigation, Assets, and Themes', 'Move between screens and keep visual configuration consistent.', 'Intermediate', ['Navigation', 'Assets', 'Themes'], 'Navigate from a task list to an editor screen.', 'dartflutter-flutter-layout-lists-forms'],
];
const advanced: Spec[] = [
 ['flutter-local-state', 'Local State and Data Loading Patterns', 'Coordinate screen state with asynchronous data without hiding loading and error states.', 'Advanced', ['State', 'Loading', 'Errors'], 'Render loading, success, and failure states from a local repository.', 'dartflutter-flutter-stateless-stateful'],
 ['flutter-state-management', 'State Management Concepts', 'Compare local, lifted, inherited, and Provider-style state without forcing a package.', 'Advanced', ['State ownership', 'Provider concepts', 'Boundaries'], 'Choose state ownership for a task feature.', 'dartflutter-flutter-local-state'],
 ['flutter-lifecycle', 'Widget Lifecycle and Cancellation', 'Tie subscriptions and controllers to lifecycle events.', 'Advanced', ['Lifecycle', 'Dispose', 'Cancellation'], 'Clean up a task stream subscription.', 'dartflutter-flutter-state-management'],
 ['flutter-performance-rebuilds', 'Performance, Rebuilds, and Keys', 'Reduce unnecessary work by understanding rebuild boundaries and stable keys.', 'Advanced', ['Rebuilds', 'Keys', 'Profiling'], 'Find and isolate an avoidable list rebuild.', 'dartflutter-flutter-stateless-stateful'],
 ['flutter-responsive', 'Responsive UI and Platform Concepts', 'Adapt layouts and platform behavior without coupling the domain to one device.', 'Advanced', ['Responsive UI', 'Platform', 'Constraints'], 'Make a task layout work at two widths.', 'dartflutter-flutter-layout-lists-forms'],
 ['flutter-persistence', 'Persistence and Offline Data Boundaries', 'Design local persistence and repository boundaries for offline-first features.', 'Advanced', ['Persistence', 'Repositories', 'Offline'], 'Define a local task repository contract.', 'dartflutter-dart-json-packages-testing'],
 ['flutter-testing', 'Flutter Widget and Integration Testing', 'Test widgets, state transitions, and user-facing flows with deterministic fixtures.', 'Advanced', ['Widget tests', 'Fixtures', 'Flows'], 'Test adding and completing a task.', 'dartflutter-flutter-local-state'],
 ['flutter-error-security', 'Error Handling and Security Basics', 'Make failures visible and protect local input, secrets, and data boundaries.', 'Advanced', ['Errors', 'Input', 'Secrets'], 'Design an error state that avoids leaking sensitive data.', 'dartflutter-flutter-persistence'],
 ['flutter-architecture', 'Flutter App Architecture', 'Separate presentation, state, domain, and persistence concerns as a feature grows.', 'Advanced', ['Architecture', 'Layers', 'Dependencies'], 'Map a task feature into clear layers.', 'dartflutter-flutter-state-management'],
 ['dartflutter-build-release', 'Build, Release, and Platform Concepts', 'Understand debug/release differences and the build artifacts a Flutter app produces.', 'Advanced', ['Builds', 'Release', 'Platforms'], 'Create a release checklist for an offline app.', 'dartflutter-flutter-architecture'],
 ['dartflutter-task-capstone', 'Dart and Flutter Learning App Capstone', 'Build an offline-friendly task or learning app with navigation, forms, state, persistence concepts, and tests.', 'Advanced', ['Capstone', 'Offline', 'Testing'], 'Plan a small Flutter learning tracker.', 'dartflutter-flutter-testing'],
 ['dartflutter-performance-review', 'Dart and Flutter Production Review', 'Review async boundaries, rebuilds, persistence, errors, and accessibility before shipping.', 'Advanced', ['Review', 'Performance', 'Quality'], 'Audit the capstone against a production checklist.', 'dartflutter-task-capstone'],
];
export const dartflutterRoadmap: LanguageRoadmap = { key: 'dartflutter', title: 'Dart / Flutter Learning Module', shortTitle: 'Dart / Flutter', subtitle: 'Dart fundamentals, declarative widgets, state, and offline-friendly Flutter apps', description: 'Learn Dart first, then build Flutter interfaces with widgets, forms, navigation, state, persistence concepts, testing, and performance awareness.', icon: 'code-outline', color: '#54C5F8', totalHours: '53h', focusAreas: ['Dart', 'Widgets', 'State', 'Offline Apps'], recommendedProject: 'Build an offline-friendly Flutter task and learning application with forms, navigation, state, and tests.', sections: [createSection({ id: 'dart-foundations', title: 'Dart Foundations', subtitle: 'Learn the language before the UI framework', topics: basic.map(make) }), createSection({ id: 'dartflutter-intermediate', title: 'Dart and Flutter Intermediate', subtitle: 'Move from data to widgets and screens', topics: intermediate.map(make) }), createSection({ id: 'dartflutter-advanced', title: 'Flutter Advanced', subtitle: 'Build resilient, maintainable applications', topics: advanced.map(make) })] };
