import { LanguageRoadmap, TopicLevel } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
type Spec = [string, string, string, TopicLevel, string[], string, string?];
const make = ([id, title, summary, level, focus, exercise, prerequisite]: Spec) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode: 'tasks = [{ title: "Read", done: false }]\nputs tasks.length', expectedResult: `A small offline Ruby example demonstrates ${title.toLowerCase()} with readable output.`, challenge: `Add an edge case related to ${title.toLowerCase()} and keep the behavior explicit.`, references: ['Ruby language', ...focus], quizQuestion: `What does ${title} help you do?`, quizAnswer: `It provides a clear Ruby pattern for ${title.toLowerCase()}.`, quizOptions: [`It provides a clear Ruby pattern for ${title.toLowerCase()}.`, 'It only changes terminal colors.', 'It removes the need for tests.'], quizExplanation: 'Ruby favors expressive code, but clear contracts and tests still matter.', prerequisites: prerequisite ? [prerequisite] : undefined });
const basic: Spec[] = [
 ['ruby-overview', 'Ruby Overview and Execution', 'Understand Ruby objects, scripts, and the interpreter-driven workflow.', 'Beginner', ['Objects', 'Scripts', 'Interpreter'], 'Run a small Ruby script from a local file.'],
 ['ruby-setup', 'Setup, irb, and Project Basics', 'Use irb and a simple project layout to experiment and build repeatably.', 'Beginner', ['irb', 'Files', 'Workflow'], 'Explore a task value in irb and then save it to a script.'],
 ['ruby-variables-types', 'Variables, Objects, and Core Types', 'Work with Ruby references and common values without confusing names and objects.', 'Beginner', ['Variables', 'Objects', 'Types'], 'Inspect task strings, numbers, and booleans.'],
 ['ruby-operators', 'Operators and Expressions', 'Compose readable expressions for comparisons and calculations.', 'Beginner', ['Expressions', 'Comparison', 'Numbers'], 'Calculate overdue task counts.'],
 ['ruby-strings-arrays', 'Strings and Arrays', 'Transform text and ordered collections with expressive Ruby methods.', 'Beginner', ['Strings', 'Arrays', 'Mutation'], 'Normalize task titles.'],
 ['ruby-hashes', 'Hashes and Symbols', 'Represent keyed data and choose symbols appropriately for stable keys.', 'Beginner', ['Hashes', 'Symbols', 'Keys'], 'Model a task as a hash.'],
 ['ruby-conditions-loops', 'Conditions and Loops', 'Use if, unless, case, and bounded loops for clear decisions.', 'Beginner', ['if', 'case', 'Loops'], 'Print labels for task states.'],
 ['ruby-iterators', 'Iterators and Enumerable Thinking', 'Use each, map, select, and reduce to express collection work.', 'Beginner', ['each', 'map', 'select'], 'Complete an enumerable task report.'],
 ['ruby-methods', 'Methods and Return Values', 'Define focused methods and understand Ruby’s implicit returns.', 'Beginner', ['Methods', 'Arguments', 'Returns'], 'Write a method that summarizes a task.'],
 ['ruby-blocks', 'Blocks and Block Parameters', 'Pass behavior to methods and make iteration contracts readable.', 'Beginner', ['Blocks', 'yield', 'Parameters'], 'Write a method that yields each task.'],
];
const intermediate: Spec[] = [
 ['ruby-classes-objects', 'Classes and Objects', 'Model behavior and state with small Ruby classes.', 'Intermediate', ['Classes', 'Objects', 'State'], 'Create a Task class with completion behavior.', 'ruby-methods'],
 ['ruby-constructors-encapsulation', 'Constructors and Encapsulation', 'Initialize valid objects and keep state changes behind methods.', 'Intermediate', ['initialize', 'Encapsulation', 'State'], 'Protect a task title and completion transition.', 'ruby-classes-objects'],
 ['ruby-inheritance', 'Inheritance and Composition', 'Choose inheritance only for genuine shared behavior and prefer composition where useful.', 'Intermediate', ['Inheritance', 'Composition', 'Design'], 'Add a timed task without duplicating the base contract.', 'ruby-classes-objects'],
 ['ruby-modules', 'Modules and Namespaces', 'Group related behavior and prevent accidental name collisions.', 'Intermediate', ['Modules', 'Namespaces', 'include'], 'Extract task formatting into a module.', 'ruby-classes-objects'],
 ['ruby-mixins', 'Mixins and Reusable Behavior', 'Use mixins carefully to share capabilities without hiding dependencies.', 'Intermediate', ['Mixins', 'Capabilities', 'Reuse'], 'Add sortable behavior to a task collection.', 'ruby-modules'],
 ['ruby-exceptions', 'Exceptions and Rescue', 'Handle expected failures while preserving useful error information.', 'Intermediate', ['Exceptions', 'rescue', 'Contracts'], 'Handle malformed task input with a custom error.', 'ruby-constructors-encapsulation'],
 ['ruby-files', 'File Handling and Persistence', 'Read and write local files for a durable offline CLI workflow.', 'Intermediate', ['File', 'IO', 'Persistence'], 'Save tasks to a simple local file.', 'ruby-exceptions'],
 ['ruby-enumerable', 'Enumerable in Depth', 'Compose lazy and eager collection operations for clear data processing.', 'Intermediate', ['Enumerable', 'Lazy', 'Pipelines'], 'Build a grouped task report.', 'ruby-iterators'],
 ['ruby-procs-lambdas', 'Procs and Lambdas', 'Compare callable objects and choose the right boundary for reusable behavior.', 'Intermediate', ['Proc', 'Lambda', 'Callable'], 'Pass a validation rule into a task service.', 'ruby-blocks'],
 ['ruby-yield', 'yield and Custom Iteration', 'Design methods that expose controlled iteration to callers.', 'Intermediate', ['yield', 'Iteration', 'API design'], 'Create a method that yields only incomplete tasks.', 'ruby-blocks'],
 ['ruby-gems-bundler', 'Gems and Bundler Concepts', 'Keep dependencies declared and project execution reproducible.', 'Intermediate', ['Gems', 'Bundler', 'Gemfile'], 'Describe a minimal dependency boundary for a CLI.'],
 ['ruby-json-http', 'JSON and HTTP/API Basics', 'Exchange structured data and keep transport concerns outside the domain model.', 'Intermediate', ['JSON', 'HTTP', 'APIs'], 'Parse an offline JSON fixture into task objects.', 'ruby-files'],
];
const advanced: Spec[] = [
 ['ruby-metaprogramming', 'Metaprogramming Introduction', 'Understand dynamic definitions and use them only when they improve clarity.', 'Advanced', ['Dynamic methods', 'DSLs', 'Tradeoffs'], 'Review a dynamic helper and replace unnecessary magic.'],
 ['ruby-reflection', 'Reflection and Introspection', 'Inspect objects deliberately while keeping runtime behavior understandable.', 'Advanced', ['Reflection', 'respond_to?', 'Design'], 'Build a safe diagnostic summary for a task.'],
 ['ruby-closures', 'Closures and Captured State', 'Reason about blocks, Procs, and the state captured by callable objects.', 'Advanced', ['Closures', 'Scope', 'State'], 'Create a configurable task predicate.', 'ruby-procs-lambdas'],
 ['ruby-threads', 'Threads and Concurrency Concepts', 'Understand shared state, scheduling, and boundaries for Ruby threads.', 'Advanced', ['Threads', 'Shared state', 'Safety'], 'Design a bounded background task operation.'],
 ['ruby-testing', 'Testing Ruby Code', 'Test models, services, file boundaries, and failure paths with deterministic data.', 'Advanced', ['Tests', 'Fixtures', 'Failures'], 'Test a file-backed task service.', 'ruby-files'],
 ['ruby-logging-performance', 'Logging and Performance', 'Add useful diagnostics and measure collection or I/O bottlenecks.', 'Advanced', ['Logging', 'Profiling', 'Performance'], 'Review a CLI for noisy logs and repeated work.', 'ruby-testing'],
 ['ruby-security-project-structure', 'Security and Ruby Project Structure', 'Validate input, protect secrets, and separate domain, service, and adapter code.', 'Advanced', ['Security', 'Structure', 'Boundaries'], 'Map a secure CLI/service layout.', 'ruby-modules'],
 ['ruby-database-rails-capstone', 'Ruby CLI and Service Capstone', 'Build a Ruby task service using OOP, modules, persistence concepts, testing, and API/data handling.', 'Advanced', ['Capstone', 'Persistence', 'Testing'], 'Plan a file-backed Ruby task CLI with a service boundary.', 'ruby-testing'],
];
export const rubyRoadmap: LanguageRoadmap = { key: 'ruby', title: 'Ruby Learning Module', shortTitle: 'Ruby', subtitle: 'Expressive scripting, object design, enumerable data, and service foundations', description: 'Learn Ruby from scripts and collections through OOP, modules, persistence, APIs, testing, and production-minded structure.', icon: 'code-outline', color: '#CC342D', totalHours: '50h', focusAreas: ['Enumerable', 'OOP', 'CLI Apps', 'APIs'], recommendedProject: 'Build a Ruby CLI or service-style task application with persistence concepts, testing, and API data handling.', sections: [createSection({ id: 'ruby-foundations', title: 'Ruby Foundations', subtitle: 'Learn the language through small scripts', topics: basic.map(make) }), createSection({ id: 'ruby-intermediate', title: 'Ruby Intermediate', subtitle: 'Build reusable object and data boundaries', topics: intermediate.map(make) }), createSection({ id: 'ruby-advanced', title: 'Ruby Advanced', subtitle: 'Prepare maintainable Ruby applications', topics: advanced.map(make) })] };
