import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
const q = (id: string, title: string, summary: string, level: 'Beginner'|'Intermediate'|'Advanced', focus: string[], exercise: string, answer: string, explanation: string, prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode: 'struct Example { int value{}; };\nExample item;', expectedResult: 'The example uses the modern C++ concept with explicit ownership and a testable result.', challenge: 'Add a boundary case and compile with warnings enabled.', references: ['C++ standard library', ...focus], quizQuestion: `Why does ${title} matter?`, quizAnswer: answer, quizOptions: [answer, 'It removes the need for all resource management.', 'It only changes terminal colors.'], quizExplanation: explanation, prerequisites });
export const cppExpansionSections: TopicSection[] = [
 createSection({ id: 'cpp-oop-stl', title: 'C++ Object Design and STL', subtitle: 'Use inheritance, templates, algorithms, and ownership', topics: [
  q('cpp-encapsulation-inheritance', 'Encapsulation and Inheritance', 'Protect invariants and reuse behavior only where the relationship is real.', 'Intermediate', ['Access control', 'Base classes', 'Composition'], 'Design a document model', 'Encapsulation protects invariants and composition is often safer than deep inheritance.', 'Good object design keeps ownership and responsibilities visible.', ['cpp-classes-lifetime']),
  q('cpp-polymorphism-virtual', 'Polymorphism, Virtual Functions, and Abstract Classes', 'Use dynamic dispatch through stable interfaces when substitution is useful.', 'Intermediate', ['virtual', 'override', 'Interfaces'], 'Create a renderer interface', 'Virtual dispatch lets a base reference call the correct derived implementation.', 'Virtual interfaces need clear ownership and virtual destruction where appropriate.'),
  q('cpp-operator-overloading', 'Operator Overloading and Namespaces', 'Make value types natural to use without surprising readers or polluting global names.', 'Intermediate', ['Operators', 'Namespaces', 'Value types'], 'Create a money value type', 'An overload should preserve familiar meaning and a namespace should prevent name collisions.', 'Convenience must not hide expensive or surprising behavior.'),
  q('cpp-templates', 'Templates, STL Containers, Iterators, and Algorithms', 'Write reusable code over types and prefer standard algorithms for common operations.', 'Intermediate', ['Templates', 'Iterators', 'Algorithms'], 'Sort a vector', 'Templates preserve type information and algorithms express common transformations.', 'STL components work together through iterator contracts.'),
  q('cpp-exceptions-files', 'Exceptions and File Handling', 'Handle failures and local persistence while preserving resource cleanup.', 'Intermediate', ['Exceptions', 'fstream', 'Error states'], 'Save a task file', 'Exceptions communicate exceptional failure while RAII closes file resources.', 'A boundary should translate exceptions into useful application behavior.'),
  q('cpp-smart-pointers-raii', 'Smart Pointers and RAII', 'Tie resource lifetime to object lifetime instead of manually coordinating cleanup.', 'Intermediate', ['unique_ptr', 'shared_ptr', 'RAII'], 'Own a dynamically created object', 'unique_ptr expresses one owner and RAII releases the resource automatically.', 'Shared ownership should be intentional because it complicates lifetime reasoning.', ['cpp-classes-lifetime']),
  q('cpp-move-rule', 'Move Semantics and Rule of 3, 5, and 0', 'Avoid unnecessary copies and understand when special member functions are needed.', 'Advanced', ['Move constructor', 'Copying', 'Rule of 0'], 'Move a buffer owner', 'Move operations transfer resources while the rule of zero prefers members that manage themselves.', 'Correct ownership is more important than forcing a move everywhere.', ['cpp-smart-pointers-raii']),
  q('cpp-lambdas-auto', 'Lambdas, auto, and Type Deduction', 'Use concise callable values and deduction without obscuring important types.', 'Intermediate', ['Lambdas', 'auto', 'Captures'], 'Filter tasks', 'A lambda captures only what it needs and auto preserves the expression type.', 'Readable deduction reduces repetition but should not hide a meaningful interface.'),
 ]}),
 createSection({ id: 'cpp-advanced', title: 'Modern C++ Advanced', subtitle: 'Compile-time tools, concurrency, memory, and quality', topics: [
  q('cpp-constexpr-templates', 'constexpr and Advanced Template Concepts', 'Move suitable calculations to compile time and introduce constraints carefully.', 'Advanced', ['constexpr', 'Type traits', 'Constraints'], 'Create a compile-time limit', 'constexpr enables compile-time evaluation when inputs and operations permit it.', 'Compile-time complexity should be justified by safety or performance.'),
  q('cpp-threads-mutex', 'Threads, Mutexes, and Concurrency Basics', 'Coordinate concurrent work and protect shared state with a clear ownership model.', 'Advanced', ['std::thread', 'mutex', 'Data races'], 'Protect a counter', 'A mutex serializes access to shared state, but minimizing shared state is often better.', 'Concurrency correctness comes before throughput.'),
  q('cpp-memory-performance', 'Memory Management and Performance', 'Measure allocations, cache behavior, and copying before optimizing a program.', 'Advanced', ['Allocation', 'Move cost', 'Profiling'], 'Measure a hot loop', 'Performance work starts with a measured bottleneck and a correctness check.', 'Low-level changes are useful only when evidence supports them.'),
  q('cpp-modern-practices', 'Modern C++ Best Practices and Security', 'Prefer safe defaults, narrow ownership, validated input, and clear interfaces.', 'Advanced', ['RAII', 'Input safety', 'Warnings'], 'Review a parser', 'Modern practices reduce leaks, unchecked input, dangling references, and unclear ownership.', 'Security and correctness are connected in systems code.'),
  q('cpp-cmake-testing-debugging', 'CMake, Testing, and Debugging', 'Create repeatable builds and use tests and debuggers to isolate defects.', 'Advanced', ['CMake', 'Tests', 'gdb'], 'Build a test target', 'A build describes targets and tests exercise public behavior with debug symbols available.', 'Automation makes native debugging repeatable.'),
 ]}),
 createSection({ id: 'cpp-capstone', title: 'C++ Applied Project', subtitle: 'Build a modern persistent console application', topics: [
  q('cpp-console-capstone', 'Modern C++ Console Capstone', 'Combine classes, STL, RAII, smart pointers, file persistence, tests, and a clear build.', 'Advanced', ['Capstone', 'STL', 'Persistence'], 'Build a task archive', 'The capstone has clear ownership, tested commands, persistence, and a maintainable CMake structure.', 'Integration demonstrates why the earlier design and ownership concepts matter.', ['cpp-smart-pointers-raii', 'cpp-cmake-testing-debugging']),
 ]}),
 createSection({ id: 'cpp-applied-practice', title: 'C++ Applied Practice', subtitle: 'Apply modern ownership and library design', topics: [
  q('cpp-copy-move-review', 'Copy and Move Review', 'Choose value, reference, and move behavior based on ownership and cost.', 'Advanced', ['Value semantics', 'Copies', 'Moves'], 'Review a resource type', 'The type has predictable copy and move behavior with no accidental double ownership.', 'Ownership semantics should be clear from the public interface.'),
  q('cpp-iterators-algorithms', 'Iterator and Algorithm Design', 'Compose standard algorithms while preserving readable predicates and complexity.', 'Intermediate', ['Iterators', 'Predicates', 'Complexity'], 'Find overdue tasks', 'A standard algorithm expresses the operation without exposing unnecessary indexing details.', 'Algorithm choice should remain understandable to the next reader.'),
  q('cpp-optional-variants', 'Optional, Variant, and Value States', 'Represent absence and alternatives without sentinel values or unsafe casts.', 'Intermediate', ['optional', 'variant', 'Visitors'], 'Model lookup results', 'The result type makes success and absence explicit to callers.', 'Standard vocabulary types reduce ambiguous state conventions.'),
  q('cpp-error-boundaries', 'Error Boundaries and Exception Safety', 'Choose error reporting and preserve object invariants when operations fail.', 'Advanced', ['Exception safety', 'Invariants', 'Results'], 'Harden a file operation', 'A failed operation leaves the object valid and communicates the failure clearly.', 'Exception safety describes what remains true when work fails.'),
  q('cpp-concurrency-review', 'Concurrency Review and Thread Safety', 'Review ownership, locks, cancellation, and data races in a threaded feature.', 'Advanced', ['Data races', 'Mutex', 'Cancellation'], 'Audit a worker queue', 'The queue has clear synchronization and a defined shutdown path.', 'Thread safety is a design property, not a patch added after a crash.'),
  q('cpp-build-portability', 'Build Portability and Dependency Boundaries', 'Use CMake targets to make include paths, libraries, and platform assumptions explicit.', 'Advanced', ['CMake targets', 'Libraries', 'Portability'], 'Split a library target', 'The build exports only intended headers and links dependencies through target relationships.', 'Target-based builds scale better than global flags.'),
  q('cpp-modern-app-capstone', 'Modern C++ Application Capstone', 'Extend the console project with search, persistence, tests, and a measured performance pass.', 'Advanced', ['Application design', 'STL', 'Review'], 'Ship a task archive', 'The application has tested commands, clear lifetime rules, and a documented performance decision.', 'A second applied pass turns isolated modern features into a maintainable product.', ['cpp-console-capstone']),
 ]}),
];
