import { LanguageRoadmap } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
import { cppExpansionSections } from './expansion';
export const cppRoadmap: LanguageRoadmap = { key: 'cpp', title: 'C++ Learning Module', shortTitle: 'C++', subtitle: 'Modern C++, STL, RAII, concurrency, and systems design', description: 'Learn modern C++ from syntax and classes through STL, ownership, move semantics, concurrency, testing, and safe application design.', icon: 'code-outline', color: '#00599C', totalHours: '46h', focusAreas: ['Modern C++', 'STL', 'RAII', 'Performance'], recommendedProject: 'Build a modern console application using classes, STL, RAII, smart pointers, and local persistence.', sections: [createSection({ id: 'cpp-foundations', title: 'C++ Foundations', subtitle: 'Write and organize first modern C++ programs', topics: [
 createCurriculumTopic({ id: 'cpp-setup-syntax', title: 'C++ Setup, Syntax, and Types', summary: 'Compile a C++ program and use values, expressions, and clear declarations.', level: 'Beginner', duration: '1h 40m', focus: ['Compiler', 'Types', 'Statements'], exercise: 'Compile a greeting program', starterCode: '#include <iostream>\nint main() { std::cout << "Hello\\n"; }', expectedResult: 'The program compiles with warnings and writes predictable output.', challenge: 'Use a separate function for the greeting.', references: ['g++ or clang++', 'iostream'], quizQuestion: 'What is the role of a compiler?', quizAnswer: 'It translates source code into a form that can be linked and run.', quizOptions: ['It translates source code into a form that can be linked and run.', 'It stores passwords.', 'It designs a database.'], quizExplanation: 'The compiler is part of the build pipeline.' }),
 createCurriculumTopic({ id: 'cpp-control-functions', title: 'Input, Operators, Conditions, Loops, and Functions', summary: 'Build reusable console logic with explicit control flow.', level: 'Beginner', duration: '1h 50m', focus: ['iostream', 'Control flow', 'Functions'], exercise: 'Build a menu', starterCode: 'for (int option = 1; option <= 3; ++option) std::cout << option << "\\n";', expectedResult: 'The menu performs repeated work and delegates operations to focused functions.', challenge: 'Validate an option before dispatching it.', references: ['Functions', 'Loops', 'iostream'], quizQuestion: 'What makes a function useful?', quizAnswer: 'It gives reusable behavior a focused contract and name.', quizOptions: ['It gives reusable behavior a focused contract and name.', 'It avoids all types.', 'It automatically persists data.'], quizExplanation: 'Functions support reuse and testing.' }),
 createCurriculumTopic({ id: 'cpp-references-strings-vectors', title: 'References, Strings, and Vectors', summary: 'Use references and standard containers instead of manual arrays where appropriate.', level: 'Beginner', duration: '1h 50m', focus: ['References', 'std::string', 'std::vector'], exercise: 'Collect lesson titles', starterCode: 'std::vector<std::string> titles{"HTML", "C++"};\nfor (const auto& title : titles) std::cout << title;', expectedResult: 'The program stores dynamic values in a standard container and reads them without unnecessary copies.', challenge: 'Pass the vector to a function by const reference.', references: ['References', 'STL containers'], quizQuestion: 'Why use a const reference parameter?', quizAnswer: 'It avoids copying while preventing the function from modifying the argument.', quizOptions: ['It avoids copying while preventing the function from modifying the argument.', 'It deletes the vector.', 'It makes all memory global.'], quizExplanation: 'Const references communicate efficient read-only access.' }),
 createCurriculumTopic({ id: 'cpp-classes-lifetime', title: 'Classes, Objects, Constructors, and Destructors', summary: 'Model state and lifetime with constructors, methods, and cleanup rules.', level: 'Beginner', duration: '2h', focus: ['Classes', 'Constructors', 'Destructors'], exercise: 'Model a Task class', starterCode: 'class Task { public: explicit Task(std::string title) : title_(std::move(title)) {} private: std::string title_; };', expectedResult: 'The class establishes valid state and its lifetime behavior is clear.', challenge: 'Add a completion method and const display method.', references: ['Classes', 'Object lifetime'], quizQuestion: 'What does a destructor represent?', quizAnswer: 'The cleanup step when an object’s lifetime ends.', quizOptions: ['The cleanup step when an object’s lifetime ends.', 'A type alias only.', 'A network request.'], quizExplanation: 'Destructors are central to resource ownership in C++.' }),
 ]}), ...cppExpansionSections] };
