import React from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/Ionicons';
import { getLanguageByKey } from '../../content/languageCatalog';
import { formatCertificateDate } from '../../learning/certificates';
import { useLearningProgress } from '../../context/LearningProgressContext';

const CertificateDetailScreen: React.FC<{ navigation: any; route: any }> = ({ navigation, route }) => {
  const progress = useLearningProgress();
  const trackKey = route.params?.trackKey;
  const certificate = trackKey ? progress.certificatesByTrack[trackKey] : undefined;
  const language = trackKey ? getLanguageByKey(trackKey) : undefined;
  const stats = trackKey ? progress.getTrackCompletion(trackKey) : undefined;
  const [name, setName] = React.useState(progress.certificateDisplayName);
  if (!certificate || !language || !stats) return <LinearGradient colors={['#0F1022', '#243B55', '#D35D6E']} style={styles.empty}><Text style={styles.emptyText}>Certificate unavailable.</Text></LinearGradient>;
  const saveName = () => { progress.saveCertificateDisplayName(name); Alert.alert('Name updated', 'The certificate view now uses this display name.'); };
  return <LinearGradient colors={['#0F1022', '#243B55', '#D35D6E']} style={styles.container}><View style={styles.content}><View style={styles.certificate} accessibilityLabel={`Certificate of Completion for ${language.shortTitle}, learner ${progress.certificateDisplayName}`}><Icon name="ribbon" size={30} color="#B77A18" /><Text style={styles.brand}>OFFLINE LEARNING HUB</Text><Text style={styles.certificateTitle}>Certificate of Completion</Text><Text style={styles.recognition}>This certificate recognizes completion of the offline learning track in</Text><Text style={styles.track}>{language.shortTitle}</Text><View style={styles.rule} /><Text style={styles.name}>{progress.certificateDisplayName}</Text><Text style={styles.recognition}>has completed the required Basic, Intermediate, and Advanced lessons.</Text><Text style={styles.date}>{formatCertificateDate(certificate.issuedAt)}</Text><Text style={styles.small}>Certificate ID: {certificate.certificateId}</Text><Text style={styles.small}>Generated locally by the app. Not an accredited professional certification.</Text></View><Text style={styles.section}>Display name</Text><TextInput value={name} onChangeText={setName} maxLength={80} accessibilityLabel="Certificate display name" style={styles.input} placeholder="Learner" placeholderTextColor="#8FA6C0" /><TouchableOpacity style={styles.save} accessibilityRole="button" accessibilityLabel="Save certificate display name" onPress={saveName}><Text style={styles.saveText}>Update Name</Text></TouchableOpacity><TouchableOpacity style={styles.back} accessibilityRole="button" accessibilityLabel="Back to certificates" onPress={() => navigation.goBack()}><Text style={styles.backText}>Back to Certificates</Text></TouchableOpacity></View></LinearGradient>;
};
export default CertificateDetailScreen;
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: 16 }, certificate: { alignItems: 'center', padding: 22, backgroundColor: '#FFFDF5', borderRadius: 6, borderWidth: 4, borderColor: '#D9B45B' }, brand: { color: '#7A5A1A', fontSize: 10, fontWeight: '800', letterSpacing: 1, marginTop: 8 }, certificateTitle: { color: '#24283A', fontSize: 24, fontWeight: '900', textAlign: 'center', marginTop: 16 }, recognition: { color: '#596273', textAlign: 'center', lineHeight: 18, marginTop: 14 }, track: { color: '#1E4E79', fontSize: 29, fontWeight: '900', marginTop: 8 }, rule: { height: 1, width: '72%', backgroundColor: '#D9B45B', marginTop: 17 }, name: { color: '#24283A', fontSize: 22, fontWeight: '800', marginTop: 14 }, date: { color: '#596273', marginTop: 16 }, small: { color: '#7C8795', textAlign: 'center', fontSize: 9, marginTop: 10 }, section: { color: '#F2F8FF', fontWeight: '800', marginTop: 20, marginBottom: 7 }, input: { minHeight: 44, padding: 12, borderRadius: 10, color: '#FFFFFF', backgroundColor: 'rgba(12,20,42,0.6)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)' }, save: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 10, borderRadius: 11, backgroundColor: 'rgba(142,203,255,0.2)' }, saveText: { color: '#FFFFFF', fontWeight: '800' }, back: { marginTop: 15, alignItems: 'center' }, backText: { color: '#C9DAEE', fontWeight: '700' }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center' }, emptyText: { color: '#F2F8FF', fontWeight: '800' } });
