import React from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import { getFlashcardsForTopic } from '../../content/practiceContent';
import { getLanguageByKey } from '../../content/languageCatalog';
import { getPracticeCandidates } from '../../content/topicIndex';
import { useLearningProgress } from '../../context/LearningProgressContext';

const FlashcardScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const progress = useLearningProgress();
  const [index, setIndex] = React.useState(0);
  const [revealed, setRevealed] = React.useState(false);
  const candidates = React.useMemo(() => getPracticeCandidates(new Set(progress.bookmarkedTopicIds.length ? progress.bookmarkedTopicIds : progress.startedTopicIds)), [progress.bookmarkedTopicIds, progress.startedTopicIds]);
  const cards = React.useMemo(() => candidates.flatMap((topic) => getFlashcardsForTopic(topic.languageKey, topic.id).slice(0, 1).map((card) => ({ ...card, topic }))), [candidates]);
  const card = cards[index];
  if (!card) return <LinearGradient colors={['#0F1022', '#243B55', '#D35D6D']} style={styles.empty}><Text style={styles.emptyTitle}>No flashcards yet</Text><Text style={styles.emptyText}>Start or save a lesson to build a local flashcard set.</Text></LinearGradient>;
  const finish = (gotIt: boolean) => { progress.recordFlashcardReview(card.topic.id, gotIt); setRevealed(false); setIndex((current) => current + 1); };
  return <LinearGradient colors={['#0F1022', '#243B55', '#D35D6D']} style={styles.container}><View style={styles.content}><Text style={styles.progress}>Card {index + 1} of {cards.length}</Text><View style={styles.card} accessibilityLabel={revealed ? `Answer: ${card.back}` : `Question: ${card.front}`}><Text style={styles.tag}>{getLanguageByKey(card.topic.languageKey)?.shortTitle ?? card.topic.languageKey}</Text><Text style={styles.front}>{card.front}</Text>{revealed ? <Text style={styles.back}>{card.back}</Text> : <TouchableOpacity style={styles.reveal} accessibilityRole="button" accessibilityLabel="Reveal flashcard answer" onPress={() => setRevealed(true)}><Text style={styles.revealText}>Reveal</Text></TouchableOpacity>}</View>{revealed ? <View style={styles.actions}><TouchableOpacity style={styles.again} accessibilityRole="button" accessibilityLabel="Mark flashcard Again" onPress={() => finish(false)}><Text style={styles.actionText}>Again</Text></TouchableOpacity><TouchableOpacity style={styles.gotIt} accessibilityRole="button" accessibilityLabel="Mark flashcard Got It" onPress={() => finish(true)}><Text style={styles.actionText}>Got It</Text></TouchableOpacity></View> : null}<TouchableOpacity accessibilityRole="button" accessibilityLabel="Back to practice" onPress={() => navigation.goBack()}><Text style={styles.backLink}>Back to practice</Text></TouchableOpacity></View></LinearGradient>;
};
export default FlashcardScreen;
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: 18 }, progress: { marginTop: 12, color: '#8ECBFF', fontWeight: '800' }, card: { minHeight: 310, marginTop: 20, padding: 20, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(12,20,42,0.7)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' }, tag: { color: '#8ECBFF', fontSize: 12, fontWeight: '800' }, front: { marginTop: 18, color: '#F2F8FF', fontSize: 23, lineHeight: 31, fontWeight: '800', textAlign: 'center' }, back: { marginTop: 24, color: '#D6E4F4', fontSize: 16, lineHeight: 24, textAlign: 'center' }, reveal: { marginTop: 28, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.14)' }, revealText: { color: '#FFFFFF', fontWeight: '800' }, actions: { flexDirection: 'row', gap: 10, marginTop: 14 }, again: { flex: 1, padding: 13, alignItems: 'center', borderRadius: 12, backgroundColor: 'rgba(255,154,154,0.2)' }, gotIt: { flex: 1, padding: 13, alignItems: 'center', borderRadius: 12, backgroundColor: 'rgba(123,216,143,0.2)' }, actionText: { color: '#FFFFFF', fontWeight: '800' }, backLink: { marginTop: 26, color: '#C9DAEE', textAlign: 'center', fontWeight: '700' }, empty: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 }, emptyTitle: { color: '#F2F8FF', fontSize: 19, fontWeight: '800' }, emptyText: { color: '#C9DAEE', marginTop: 8, textAlign: 'center', lineHeight: 20 } });
