import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/Ionicons';
import { getLearningGoal } from '../../learning/learningGoals';
import { generateTodayPlan, getCurrentStage, getGoalProgress } from '../../learning/learningPlan';
import { useLearningProgress } from '../../context/LearningProgressContext';

const LearningPlanScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const progress = useLearningProgress();
  const goal = getLearningGoal(progress.learningGoal);
  const completed = React.useMemo(() => new Set(progress.completedTopicIds), [progress.completedTopicIds]);
  const plan = React.useMemo(() => generateTodayPlan(goal, completed, new Set(progress.reviewTopicIds), new Set(progress.getWeakTopicIds()), progress.dailyStudyMinutes), [completed, goal, progress.dailyStudyMinutes, progress.getWeakTopicIds, progress.reviewTopicIds]);
  const path = goal ? getGoalProgress(goal, completed) : { completed: 0, total: 0, percent: 0 };
  const stage = goal ? getCurrentStage(goal, completed) : undefined;
  const open = (item: typeof plan[number]) => { const params = { languageKey: item.topic.languageKey, topicId: item.topic.id }; navigation.navigate(item.type === 'practice' ? 'PracticeScreen' : item.type === 'code' ? 'CodePlayground' : 'LearningTopicDetail', params); };
  return <LinearGradient colors={['#0F1022', '#243B55', '#D35D6E']} style={styles.container}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.eyebrow}>Your Plan</Text><Text style={styles.heading}>{goal?.title ?? 'Choose a learning goal'}</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Open plan settings" onPress={() => navigation.navigate('PlanSettings')}><Icon name="options-outline" size={22} color="#FFFFFF" /></TouchableOpacity></View>{goal ? <><Text style={styles.description}>{goal.description}</Text><View style={styles.summary} accessibilityLabel={`${path.percent}% goal progress, stage ${stage!.index + 1} of ${goal.stages.length}`}><Text style={styles.stage}>Stage {stage!.index + 1} of {goal.stages.length} - {stage!.stage.title}</Text><Text style={styles.percent}>{path.percent}% complete</Text><View style={styles.bar}><View style={[styles.fill, { width: `${path.percent}%` }]} /></View><Text style={styles.meta}>{progress.dailyStudyMinutes} minutes per day</Text></View><Text style={styles.section}>Today's Plan</Text>{plan.length ? plan.map((item) => <TouchableOpacity key={item.id} style={styles.item} accessibilityRole="button" accessibilityLabel={`${item.type} ${item.topic.title}, ${item.reason}`} onPress={() => open(item)}><View style={styles.itemBody}><Text style={styles.itemType}>{item.type.toUpperCase()} - {item.reason}</Text><Text style={styles.itemTitle}>{item.topic.title}</Text><Text style={styles.itemMeta}>{item.topic.languageName} | {item.topic.duration}</Text></View><Icon name="chevron-forward" size={18} color="#C9DAEE" /></TouchableOpacity>) : <Text style={styles.empty}>This path is complete. Review weak topics or choose another goal.</Text>}<Text style={styles.section}>Upcoming Stages</Text>{goal.stages.map((item, index) => <View key={item.id} style={[styles.stageRow, index === stage!.index && styles.current]}><Text style={styles.stageName}>{index + 1}. {item.title}</Text><Text style={styles.stageMeta}>{index < stage!.index ? 'Complete' : index === stage!.index ? 'Current' : 'Upcoming'}</Text></View>)}</> : <TouchableOpacity style={styles.primary} accessibilityRole="button" accessibilityLabel="Build my learning plan" onPress={() => navigation.navigate('PlanSettings')}><Text style={styles.primaryText}>Build My Learning Plan</Text></TouchableOpacity>}</ScrollView></LinearGradient>;
};
export default LearningPlanScreen;
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: 16, paddingBottom: 40 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: '#8ECBFF', fontWeight: '800', fontSize: 11 }, heading: { color: '#F2F8FF', fontSize: 25, fontWeight: '800', marginTop: 4 }, description: { color: '#C9DAEE', marginTop: 9, lineHeight: 19 }, summary: { padding: 15, marginTop: 16, borderRadius: 14, backgroundColor: 'rgba(12,20,42,0.6)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)' }, stage: { color: '#F2F8FF', fontWeight: '800' }, percent: { color: '#FFD27A', fontWeight: '800', marginTop: 7 }, bar: { height: 8, borderRadius: 5, marginTop: 11, overflow: 'hidden', backgroundColor: 'rgba(255,255,255,0.12)' }, fill: { height: '100%', backgroundColor: '#8ECBFF' }, meta: { color: '#BFD2E8', fontSize: 11, marginTop: 7 }, section: { color: '#F2F8FF', fontSize: 17, fontWeight: '800', marginTop: 21, marginBottom: 10 }, item: { flexDirection: 'row', alignItems: 'center', padding: 14, marginBottom: 9, borderRadius: 13, backgroundColor: 'rgba(12,20,42,0.58)' }, itemBody: { flex: 1 }, itemType: { color: '#8ECBFF', fontSize: 10, fontWeight: '800' }, itemTitle: { color: '#F2F8FF', fontWeight: '800', marginTop: 5 }, itemMeta: { color: '#BFD2E8', fontSize: 11, marginTop: 5 }, empty: { color: '#D6E4F4', lineHeight: 20 }, stageRow: { flexDirection: 'row', justifyContent: 'space-between', padding: 13, marginBottom: 7, borderRadius: 11, backgroundColor: 'rgba(12,20,42,0.42)' }, current: { borderWidth: 1, borderColor: '#8ECBFF' }, stageName: { color: '#F2F8FF', fontWeight: '700' }, stageMeta: { color: '#BFD2E8', fontSize: 11 }, primary: { padding: 16, marginTop: 20, borderRadius: 13, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.18)' }, primaryText: { color: '#FFFFFF', fontWeight: '800' } });
