import React from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import { LEARNING_GOALS, type ExperienceLevel, type LearningGoalId } from '../../learning/learningGoals';
import { useLearningProgress } from '../../context/LearningProgressContext';

const experiences: Array<[ExperienceLevel, string]> = [['beginner', 'Complete Beginner'], ['some-basics', 'Some Basics'], ['intermediate', 'Intermediate'], ['experienced', 'Experienced']];
const minutes = [10, 20, 30, 45, 60];
const OnboardingScreen: React.FC<{ navigation: any; route?: any }> = ({ navigation, route }) => {
  const progress = useLearningProgress();
  const settings = route?.params?.settings === true;
  const [step, setStep] = React.useState(0);
  const [experience, setExperience] = React.useState<ExperienceLevel>(progress.experienceLevel ?? 'beginner');
  const [goal, setGoal] = React.useState<LearningGoalId>((progress.learningGoal as LearningGoalId) ?? 'general-programming');
  const [studyMinutes, setStudyMinutes] = React.useState(progress.dailyStudyMinutes || 30);
  const finish = (completed: boolean) => { progress.saveLearningPreferences({ onboardingCompleted: completed, experienceLevel: experience, learningGoal: completed || settings ? goal : progress.learningGoal, dailyStudyMinutes: studyMinutes }); navigation.replace('LearningPlan'); };
  const titles = ['Your experience', 'Your direction', 'Your daily time'];
  return <LinearGradient colors={['#0F1022', '#243B55', '#D35D6E']} style={styles.container}><View style={styles.content}><Text style={styles.heading}>{settings ? 'Plan Settings' : 'Build Your Learning Plan'}</Text><Text style={styles.progress}>Step {step + 1} of 3</Text><Text style={styles.question}>{titles[step]}</Text>{step === 0 ? experiences.map(([key, label]) => <TouchableOpacity key={key} style={[styles.option, experience === key && styles.selected]} accessibilityRole="radio" accessibilityState={{ selected: experience === key }} accessibilityLabel={label} onPress={() => setExperience(key)}><Text style={styles.optionText}>{label}</Text></TouchableOpacity>) : null}{step === 1 ? LEARNING_GOALS.map((item) => <TouchableOpacity key={item.id} style={[styles.option, goal === item.id && styles.selected]} accessibilityRole="radio" accessibilityState={{ selected: goal === item.id }} accessibilityLabel={item.title} onPress={() => setGoal(item.id)}><Text style={styles.optionText}>{item.title}</Text><Text style={styles.optionSubtext}>{item.description}</Text></TouchableOpacity>) : null}{step === 2 ? minutes.map((value) => <TouchableOpacity key={value} style={[styles.option, studyMinutes === value && styles.selected]} accessibilityRole="radio" accessibilityState={{ selected: studyMinutes === value }} accessibilityLabel={`${value} minutes per day`} onPress={() => setStudyMinutes(value)}><Text style={styles.optionText}>{value} minutes per day</Text></TouchableOpacity>) : null}<View style={styles.actions}>{step > 0 ? <TouchableOpacity style={styles.secondary} accessibilityRole="button" accessibilityLabel="Go back" onPress={() => setStep(step - 1)}><Text style={styles.actionText}>Back</Text></TouchableOpacity> : null}<TouchableOpacity style={styles.secondary} accessibilityRole="button" accessibilityLabel="Skip personalization" onPress={() => finish(false)}><Text style={styles.actionText}>Skip</Text></TouchableOpacity><TouchableOpacity style={styles.primary} accessibilityRole="button" accessibilityLabel={step === 2 ? 'Build learning plan' : 'Continue'} onPress={() => step === 2 ? finish(true) : setStep(step + 1)}><Text style={styles.actionText}>{step === 2 ? 'Build Plan' : 'Continue'}</Text></TouchableOpacity></View></View></LinearGradient>;
};
export default OnboardingScreen;
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: 18, paddingTop: 30 }, heading: { color: '#F2F8FF', fontSize: 25, fontWeight: '800' }, progress: { color: '#8ECBFF', marginTop: 10, fontWeight: '800' }, question: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', marginTop: 24, marginBottom: 14 }, option: { padding: 15, marginBottom: 10, borderRadius: 13, backgroundColor: 'rgba(12,20,42,0.6)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.16)' }, selected: { borderColor: '#8ECBFF', backgroundColor: 'rgba(142,203,255,0.18)' }, optionText: { color: '#F2F8FF', fontWeight: '800' }, optionSubtext: { color: '#C9DAEE', fontSize: 11, marginTop: 5 }, actions: { flexDirection: 'row', gap: 8, marginTop: 18 }, primary: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.18)' }, secondary: { minHeight: 46, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(12,20,42,0.55)' }, actionText: { color: '#FFFFFF', fontWeight: '800' } });
