import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
const q = (id: string, title: string, summary: string, level: 'Beginner'|'Intermediate'|'Advanced', prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus: ['PHP design', 'Practical exercise', 'Safe handling'], exercise: `Build a local ${title.toLowerCase()} example`, starterCode: '<?php\n$items = ["lesson"];\necho count($items);', expectedResult: `The example demonstrates ${title.toLowerCase()} with a clear result and handled input.`, challenge: 'Add a boundary case and a focused test.', references: ['PHP manual', 'HTTP basics', title], quizQuestion: `Why is ${title} useful?`, quizAnswer: 'It gives a clear PHP pattern for the problem it addresses.', quizOptions: ['It gives a clear PHP pattern for the problem it addresses.', 'It only changes colors.', 'It makes all input trusted.'], quizExplanation: 'A good practice improves correctness, security, or maintainability.', prerequisites });
export const phpExpansionSections: TopicSection[] = [
 createSection({ id: 'php-web-intermediate', title: 'PHP Web Development', subtitle: 'Handle forms, state, files, and object design', topics: [
  q('php-forms-get-post', 'Forms, GET, and POST', 'Read request input and distinguish query parameters from submitted data.', 'Beginner'), q('php-includes', 'Includes and Requires', 'Share configuration and reusable code without hidden execution surprises.', 'Beginner'), q('php-associative-arrays', 'Associative Arrays and Data Shaping', 'Represent records and transform nested request data.', 'Intermediate'), q('php-files-json', 'File Handling and JSON', 'Persist simple local data with explicit encoding and error checks.', 'Intermediate'), q('php-sessions-cookies', 'Sessions and Cookies', 'Maintain state while understanding trust and expiration boundaries.', 'Intermediate'), q('php-oop', 'Classes, Objects, Constructors, and Encapsulation', 'Model related data and behavior with controlled state.', 'Intermediate'), q('php-inheritance-interfaces-traits', 'Inheritance, Interfaces, and Traits', 'Reuse contracts carefully without hiding dependencies.', 'Intermediate'),
 ]}),
 createSection({ id: 'php-data-api', title: 'PHP Data and APIs', subtitle: 'Connect secure input to persistence and HTTP responses', topics: [
  q('php-exceptions-namespaces', 'Exceptions and Namespaces', 'Organize classes and report failures with useful context.', 'Intermediate'), q('php-composer', 'Composer and Dependency Management', 'Install and autoload packages with repeatable project metadata.', 'Intermediate'), q('php-http-json', 'HTTP, JSON, and API Basics', 'Return predictable status codes and JSON response shapes.', 'Intermediate'), q('php-pdo', 'PDO and Database Access', 'Use a database abstraction with explicit connection and failure handling.', 'Intermediate'), q('php-prepared-statements', 'Prepared Statements', 'Keep SQL syntax separate from untrusted values.', 'Advanced', ['php-pdo']), q('php-validation', 'Validation and Error Responses', 'Reject invalid input close to the request boundary.', 'Advanced'), q('php-auth-hashing', 'Authentication and Password Hashing', 'Design identity flows without storing plain-text credentials.', 'Advanced'),
 ]}),
 createSection({ id: 'php-secure-architecture', title: 'PHP Advanced Practice', subtitle: 'Build safer, testable, and deployable applications', topics: [
  q('php-csrf-xss-sql', 'CSRF, XSS, and SQL Injection Prevention', 'Protect forms, output, and database queries against common web attacks.', 'Advanced'), q('php-mvc-routing', 'MVC and Routing Concepts', 'Separate request routing, application logic, and presentation.', 'Advanced'), q('php-rest-structure', 'REST API Structure', 'Organize resources, validation, pagination, and consistent errors.', 'Advanced'), q('php-testing-logging', 'Testing and Logging', 'Verify behavior and diagnose failures without logging secrets.', 'Advanced'), q('php-caching-performance', 'Caching and Performance', 'Reduce repeated work while documenting freshness and invalidation.', 'Advanced'), q('php-deployment-env', 'Deployment, Configuration, and Environment Variables', 'Keep production settings outside committed source and deploy repeatably.', 'Advanced'), q('php-crud-capstone', 'Secure PHP CRUD/API Capstone', 'Build a small PDO-backed project with validation, sessions, secure output, and tests.', 'Advanced', ['php-prepared-statements', 'php-validation', 'php-testing-logging']),
 ]}),
 createSection({ id: 'php-applied-practice', title: 'PHP Applied Practice', subtitle: 'Reinforce secure request handling', topics: [
  q('php-api-errors', 'API Error Contract Exercise', 'Return consistent JSON errors for invalid CRUD requests.', 'Intermediate'),
 ]}),
];
