import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
const q = (id: string, title: string, summary: string, level: 'Beginner'|'Intermediate'|'Advanced', prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus: ['C# design', 'Practical exercise', 'Maintainability'], exercise: `Build a local ${title.toLowerCase()} example`, starterCode: 'var items = new List<string> { "lesson" };\nConsole.WriteLine(items.Count);', expectedResult: `The example demonstrates ${title.toLowerCase()} with a clear result and a handled edge case.`, challenge: `Extend the ${title.toLowerCase()} exercise with validation and a focused test.`, references: ['C# documentation', '.NET API', title], quizQuestion: `Why is ${title} useful?`, quizAnswer: `It gives a clear C# pattern for the problem it addresses.`, quizOptions: [`It gives a clear C# pattern for the problem it addresses.`, 'It only changes terminal colors.', 'It removes the need for error handling.'], quizExplanation: 'A useful language feature improves correctness, clarity, reuse, or operational behavior.', prerequisites });
export const csharpExpansionSections: TopicSection[] = [
 createSection({ id: 'csharp-oop-collections', title: 'C# Intermediate', subtitle: 'Use object design, collections, and data transformations', topics: [
  q('csharp-encapsulation', 'Encapsulation and Access', 'Protect invariants with private state and deliberate public members.', 'Intermediate'), q('csharp-inheritance-polymorphism', 'Inheritance and Polymorphism', 'Use substitution and overrides where a shared abstraction is real.', 'Intermediate'), q('csharp-interfaces-abstract', 'Interfaces and Abstract Classes', 'Define capabilities and partial contracts for related types.', 'Intermediate'), q('csharp-enums-structs', 'Enums and Structs', 'Represent finite states and small value types appropriately.', 'Intermediate'), q('csharp-collections', 'List, Dictionary, and HashSet', 'Choose collections for ordered values, lookup, and uniqueness.', 'Intermediate'), q('csharp-generics', 'Generics', 'Preserve type information across reusable classes and methods.', 'Intermediate'), q('csharp-exceptions-files', 'Exceptions and File Handling', 'Handle expected failures and persist local text or JSON files.', 'Intermediate'),
 ]}),
 createSection({ id: 'csharp-language-tools', title: 'C# Language Tools', subtitle: 'Compose queries, callbacks, and nullable-safe code', topics: [
  q('csharp-linq', 'LINQ Basics', 'Filter, project, sort, and group collections with readable query pipelines.', 'Intermediate', ['csharp-collections', 'csharp-lambdas']), q('csharp-delegates-events', 'Delegates and Events', 'Pass behavior and publish changes without tightly coupling listeners.', 'Intermediate'), q('csharp-lambdas', 'Lambda Expressions', 'Write small functions for collection operations and callbacks.', 'Intermediate', ['csharp-classes-properties']), q('csharp-nullable', 'Nullable Reference Types', 'Make absent reference values visible and reduce null failures.', 'Intermediate'), q('csharp-async-tasks', 'async/await and Tasks', 'Coordinate asynchronous work while propagating errors and cancellation.', 'Advanced'), q('csharp-di', 'Dependency Injection Concepts', 'Separate construction from use so services are replaceable and testable.', 'Advanced', ['csharp-interfaces-abstract']), q('csharp-records-patterns', 'Records and Pattern Matching', 'Model immutable data and branch on shape or state clearly.', 'Advanced'),
 ]}),
 createSection({ id: 'csharp-production', title: 'C# Advanced Practice', subtitle: 'Connect .NET code to APIs, persistence, and quality', topics: [
  q('csharp-reflection-attributes', 'Reflection and Attributes', 'Understand metadata-driven behavior and its runtime tradeoffs.', 'Advanced'), q('csharp-serialization-http', 'Serialization and HTTP/API Usage', 'Exchange validated JSON data across application boundaries.', 'Advanced'), q('csharp-testing-logging', 'Testing and Logging', 'Verify behavior and diagnose failures without leaking sensitive data.', 'Advanced'), q('csharp-ef-database', 'Entity Framework and Database Concepts', 'Understand ORM mapping, queries, migrations, and database boundaries.', 'Advanced'), q('csharp-performance-gc-security', 'Performance, Memory, GC, and Security Basics', 'Measure managed allocations and protect input and secrets.', 'Advanced'), q('csharp-architecture', '.NET Project Architecture', 'Separate domain, application, infrastructure, and interface concerns.', 'Advanced'), q('csharp-management-capstone', 'C# Management API Capstone', 'Build an OOP management service with collections, validation, persistence concepts, async work, and tests.', 'Advanced', ['csharp-linq', 'csharp-async-tasks', 'csharp-testing-logging']),
 ]}),
 createSection({ id: 'csharp-applied-practice', title: 'C# Applied Practice', subtitle: 'Reinforce validation and feature delivery', topics: [
  q('csharp-cli-validation', 'Collection Manager Validation Exercise', 'Combine collections, validation, and clear console feedback in a small management workflow.', 'Intermediate'),
 ]}),
];
