import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';

const q = (id: string, title: string, summary: string, level: 'Beginner' | 'Intermediate' | 'Advanced', focus: string[], exercise: string, answer: string, options: string[], explanation: string, prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode: 'type Lesson = { id: string; title: string };\nconst lesson: Lesson = { id: "ts-1", title: "Types" };', expectedResult: 'The example models the data boundary clearly and the compiler gives useful feedback as it changes.', challenge: 'Add one edge case and explain whether compile-time or runtime validation should handle it.', references: ['TypeScript handbook', ...focus], quizQuestion: `What is the main idea in ${title}?`, quizAnswer: answer, quizOptions: options, quizExplanation: explanation, prerequisites });
const yes = (answer: string, wrong: string, explanation: string) => [answer, wrong, 'It only changes CSS.'];

export const typescriptExpansionSections: TopicSection[] = [
  createSection({ id: 'typescript-basic-types', title: 'TypeScript Type Building', subtitle: 'Model everyday values and object contracts', topics: [
    q('typescript-primitives-arrays', 'Primitive Types, Arrays, and Tuples', 'Represent simple values, repeated values, and fixed-position records accurately.', 'Beginner', ['string and number', 'Arrays', 'Tuples'], 'Type a course row', 'Tuple types describe fixed positions and arrays describe repeated values.', yes('Tuple types describe fixed positions and arrays describe repeated values.', 'All arrays are tuples.', 'Types describe intended shapes.'), 'Arrays and tuples communicate different guarantees.'),
    q('typescript-objects', 'Object Types and Optional Properties', 'Describe object fields, readonly values, and fields that may be absent.', 'Beginner', ['Object types', 'readonly', 'Optional fields'], 'Model a profile', 'An object type documents required and optional properties.', yes('An object type documents required and optional properties.', 'Objects cannot have optional fields.', 'Types are only comments.'), 'Optional does not mean the property exists with undefined in every runtime situation.'),
    q('typescript-unions-literals', 'Union and Literal Types', 'Limit a value to several valid alternatives or an exact set of states.', 'Beginner', ['Unions', 'Literals', 'State models'], 'Type a lesson status', 'A union models a finite set of allowed values.', yes('A union models a finite set of allowed values.', 'A union accepts every value.', 'A union creates a database.'), 'Unions make invalid states harder to express.'),
    q('typescript-aliases-interfaces', 'Type Aliases and Interfaces', 'Name reusable contracts and choose an appropriate extension style.', 'Beginner', ['Aliases', 'Interfaces', 'Composition'], 'Share a lesson contract', 'A named contract can be reused across functions and modules.', yes('A named contract can be reused across functions and modules.', 'Names remove all runtime checks.', 'Interfaces are HTML tags.'), 'Both forms describe shapes; project conventions guide which one to use.'),
  ]}),
  createSection({ id: 'typescript-intermediate', title: 'TypeScript Intermediate', subtitle: 'Narrow values and build reusable type APIs', topics: [
    q('typescript-narrowing', 'Narrowing and Type Guards', 'Turn broad input types into safe branches using runtime checks.', 'Intermediate', ['typeof', 'in', 'Guards'], 'Handle unknown JSON', 'Narrowing proves which operations are safe in each branch.', yes('Narrowing proves which operations are safe in each branch.', 'Narrowing encrypts input.', 'Narrowing skips runtime checks.'), 'TypeScript follows checks such as typeof and custom predicates.'),
    q('typescript-enums-alternatives', 'Enums and Union Alternatives', 'Compare enums with literal unions and choose a representation that fits the data.', 'Intermediate', ['Enums', 'Literal unions', 'Serialization'], 'Model status values', 'A literal union often maps directly to JSON without an emitted enum object.', yes('A literal union often maps directly to JSON without an emitted enum object.', 'Enums only work in CSS.', 'Unions always emit JavaScript.'), 'Runtime needs and serialization shape matter when selecting a model.'),
    q('typescript-generics', 'Generics and Generic Constraints', 'Write reusable functions that preserve relationships between input and output types.', 'Intermediate', ['Type parameters', 'Constraints', 'Reusable APIs'], 'Build a typed identity helper', 'Generics preserve a value type through a reusable operation.', yes('Generics preserve a value type through a reusable operation.', 'Generics mean any is always safe.', 'Generics run queries.'), 'Constraints limit generic inputs to operations the implementation needs.', ['typescript-functions']),
    q('typescript-keyof-typeof', 'keyof, typeof, and Indexed Access', 'Derive types from existing models instead of duplicating property names.', 'Intermediate', ['keyof', 'typeof', 'Indexed access'], 'Type a field picker', 'Derived keys stay synchronized when the source object changes.', yes('Derived keys stay synchronized when the source object changes.', 'keyof reads a file.', 'typeof deletes properties.'), 'Type queries reduce drift between values and their types.'),
    q('typescript-utility-types', 'Utility Types', 'Transform existing contracts with Partial, Pick, Omit, Record, and Readonly.', 'Intermediate', ['Partial', 'Pick and Omit', 'Record'], 'Create an update payload', 'An update model can require only fields that are allowed to change.', yes('An update model can require only fields that are allowed to change.', 'Utility types validate passwords.', 'Partial makes every runtime field present.'), 'Utility types transform compile-time contracts; runtime validation remains separate.'),
    q('typescript-modules-classes', 'Modules, Classes, and Access Modifiers', 'Organize typed code and use public, private, and protected boundaries carefully.', 'Intermediate', ['Modules', 'Classes', 'Modifiers'], 'Split a repository class', 'A module exports a focused class while its internal fields stay protected.', yes('A module exports a focused class while its internal fields stay protected.', 'Private fields are global.', 'Modules require a server.'), 'Access modifiers communicate intended ownership to TypeScript users.'),
    q('typescript-overloads-declarations', 'Function Overloads and Declaration Files', 'Describe multiple call signatures and add types for JavaScript libraries without bundled types.', 'Intermediate', ['Overloads', '.d.ts', 'Library boundaries'], 'Type a legacy helper', 'Overloads describe valid call forms while a declaration file describes external JavaScript.', yes('Overloads describe valid call forms while a declaration file describes external JavaScript.', 'Declarations execute business logic.', 'Overloads remove tests.'), 'Declaration files are contracts, not implementations.'),
  ]}),
  createSection({ id: 'typescript-advanced', title: 'TypeScript Advanced', subtitle: 'Express complex relationships and configure safe builds', topics: [
    q('typescript-conditional-mapped', 'Conditional and Mapped Types', 'Build types that branch or transform keys systematically.', 'Advanced', ['Conditional types', 'Mapped types', 'Modifiers'], 'Create a readonly model', 'Mapped types iterate over keys while conditional types choose a result.', yes('Mapped types iterate over keys while conditional types choose a result.', 'Mapped types loop at runtime.', 'Conditional types are CSS rules.'), 'These features are powerful but should remain readable.'),
    q('typescript-template-literals', 'Template Literal Types', 'Constrain string formats and derive event or route names from models.', 'Advanced', ['Template strings', 'String unions', 'Derived APIs'], 'Type route names', 'Template literal types compose allowed string fragments.', yes('Template literal types compose allowed string fragments.', 'They parse network traffic.', 'They replace all validation.'), 'They help model conventions such as event names at compile time.'),
    q('typescript-infer-predicates', 'infer and Type Predicates', 'Extract related types and teach the compiler what a custom runtime check proves.', 'Advanced', ['infer', 'Predicates', 'Reusable guards'], 'Write an API response guard', 'A predicate returns a boolean and narrows the checked value for callers.', yes('A predicate returns a boolean and narrows the checked value for callers.', 'Predicates are database indexes.', 'infer runs code.'), 'Runtime evidence and compile-time narrowing work together.'),
    q('typescript-discriminated-unions', 'Discriminated Unions and Error Models', 'Represent mutually exclusive states so incomplete handling becomes visible.', 'Advanced', ['Discriminants', 'Exhaustiveness', 'Error states'], 'Model request state', 'A status field lets a switch narrow the matching payload fields.', yes('A status field lets a switch narrow the matching payload fields.', 'Unions hide all states.', 'Errors should be strings only.'), 'Discriminants create explicit and exhaustively checkable state machines.'),
    q('typescript-strict-performance', 'Strict Mode and Build Performance', 'Use strict compiler settings and keep type-checking fast as a project grows.', 'Advanced', ['strict', 'Project references', 'Incremental builds'], 'Review compiler settings', 'Strict checks expose unsafe assumptions while incremental builds avoid repeated work.', yes('Strict checks expose unsafe assumptions while incremental builds avoid repeated work.', 'Strict mode disables TypeScript.', 'Build speed depends only on CSS.'), 'Good configuration balances safety, feedback time, and project boundaries.'),
    q('typescript-api-models', 'Type-Safe API Models and Error Handling', 'Pair compile-time response models with runtime validation at external boundaries.', 'Advanced', ['DTOs', 'Runtime schemas', 'Error handling'], 'Design an API boundary', 'External JSON is unknown until validated, then converted into an internal model.', yes('External JSON is unknown until validated, then converted into an internal model.', 'Type annotations validate network data automatically.', 'APIs never fail.'), 'Types cannot inspect untrusted runtime JSON by themselves.'),
    q('typescript-react-node-testing', 'TypeScript with React, Node, and Tests', 'Apply shared types across UI, backend, and tests without coupling unrelated layers.', 'Advanced', ['React props', 'Node handlers', 'Testing'], 'Type a feature boundary', 'A shared domain model supports the feature while each layer owns its adapter types.', yes('A shared domain model supports the feature while each layer owns its adapter types.', 'One type replaces every test.', 'React and Node share a runtime.'), 'Type reuse should clarify contracts, not force every layer into one shape.'),
    q('typescript-data-capstone', 'TypeScript Type-Safe Data App Capstone', 'Build a data-management project using models, generics, narrowing, API boundaries, and tests.', 'Advanced', ['Capstone planning', 'Safe boundaries', 'Testing'], 'Build a typed lesson manager', 'The capstone combines typed state, validated input, reusable utilities, and tested failure paths.', yes('The capstone combines typed state, validated input, reusable utilities, and tested failure paths.', 'A capstone needs no model.', 'Types remove the need for design.'), 'The final project demonstrates decisions across the whole TypeScript workflow.', ['typescript-generics', 'typescript-api-models']),
  ]}),
  createSection({ id: 'typescript-applied', title: 'TypeScript Applied Practice', subtitle: 'Use types at real application boundaries', topics: [
    q('typescript-json-validation', 'Runtime Validation for JSON', 'Validate unknown external data before treating it as an internal type.', 'Advanced', ['unknown', 'Validation', 'Boundaries'], 'Validate a response', 'External JSON must be checked at runtime before a static model is trusted.', yes('External JSON must be checked at runtime before a static model is trusted.', 'Types validate runtime data automatically.', 'Runtime checks protect external input.'), 'Static types describe compiled code; runtime validation protects external input.', ['typescript-api-models']),
    q('typescript-node-config', 'Type-Safe Node Configuration', 'Model environment configuration and fail clearly when required values are absent.', 'Advanced', ['Config', 'Environment', 'Errors'], 'Type a config loader', 'Configuration is parsed once and exposed through a small typed interface.', yes('Configuration is parsed once and exposed through a small typed interface.', 'Configuration never needs checking.', 'Typed configuration makes startup assumptions visible.'), 'Typed configuration makes startup assumptions visible.'),
    q('typescript-react-props', 'React Props and Event Types', 'Use precise props and event types without coupling components to implementation details.', 'Intermediate', ['Props', 'Events', 'Components'], 'Type a form component', 'Props describe the component contract and event handlers receive the expected event shape.', yes('Props describe the component contract and event handlers receive the expected event shape.', 'Props should be any.', 'Local component contracts keep UI changes safer.'), 'Local component contracts keep UI changes safer.', ['typescript-functions']),
    q('typescript-release-capstone', 'Type-Safe Data Management Capstone', 'Deliver a small application with typed models, validation, tests, and a measured build.', 'Advanced', ['Release review', 'Models', 'Tests'], 'Ship a typed app', 'A complete project combines type design with runtime behavior and tests.', yes('A complete project combines type design with runtime behavior and tests.', 'A capstone needs no model.', 'The capstone proves types support a product workflow.'), 'The capstone proves types support a product workflow rather than existing in isolation.', ['typescript-json-validation', 'typescript-react-node-testing']),
  ]}),
];
