import { LanguageRoadmap } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
import { typescriptExpansionSections } from './expansion';

export const typescriptRoadmap: LanguageRoadmap = {
  key: 'typescript', title: 'TypeScript Learning Module', shortTitle: 'TypeScript',
  subtitle: 'Typed JavaScript, expressive models, and safer application architecture',
  description: 'Learn TypeScript from annotations and inference through advanced type modeling and type-safe application design.',
  icon: 'code-slash-outline', color: '#3178C6', totalHours: '42h', focusAreas: ['Types', 'Generics', 'Tooling', 'Safe Apps'],
  recommendedProject: 'Build a type-safe data management app with validated models, reusable utilities, and tested API boundaries.',
  sections: [createSection({ id: 'typescript-foundations', title: 'TypeScript Foundations', subtitle: 'Start with typed JavaScript and clear data contracts', topics: [
    createCurriculumTopic({ id: 'typescript-why', title: 'Why TypeScript and How It Works', summary: 'Understand the problems static checking solves and what happens before JavaScript runs.', level: 'Beginner', duration: '1h 20m', focus: ['Static checking', 'JavaScript relationship', 'Compiler output'], exercise: 'Compare typed and untyped input', starterCode: 'function greet(name: string) { return `Hello ${name}`; }', expectedResult: 'The compiler catches an invalid call while the emitted JavaScript remains ordinary runtime code.', challenge: 'Find one bug that types catch and one runtime bug they cannot catch.', references: ['TypeScript compiler', 'JavaScript compatibility'], quizQuestion: 'When are most TypeScript types checked?', quizAnswer: 'During development and compilation, before the JavaScript runs.', quizOptions: ['During development and compilation, before the JavaScript runs.', 'Only after deployment.', 'Only by the browser.'], quizExplanation: 'TypeScript adds static analysis; it does not replace runtime validation.' }),
    createCurriculumTopic({ id: 'typescript-setup', title: 'Setup, Compiler, and tsconfig', summary: 'Create a repeatable TypeScript project and understand its compiler entry points.', level: 'Beginner', duration: '1h 30m', focus: ['tsc', 'tsconfig', 'Source and output'], exercise: 'Configure a small project', starterCode: '{ "compilerOptions": { "target": "ES2020", "strict": true, "outDir": "dist" } }', expectedResult: 'Source files compile to a predictable output directory with strict checks enabled.', challenge: 'Add an include rule and exclude generated output.', references: ['tsconfig', 'tsc', 'Compiler options'], quizQuestion: 'What does tsconfig describe?', quizAnswer: 'How the TypeScript compiler should check and emit a project.', quizOptions: ['How the TypeScript compiler should check and emit a project.', 'The database schema only.', 'The browser layout.'], quizExplanation: 'tsconfig makes compiler behavior explicit and repeatable.' }),
    createCurriculumTopic({ id: 'typescript-annotations-inference', title: 'Annotations and Type Inference', summary: 'Add types where they clarify intent and let the compiler infer obvious local values.', level: 'Beginner', duration: '1h 35m', focus: ['Annotations', 'Inference', 'Avoiding any'], exercise: 'Type a lesson record', starterCode: 'const title: string = "Functions";\nconst minutes = 30;', expectedResult: 'Important boundaries are annotated while simple locals use accurate inferred types.', challenge: 'Replace an any value with an explicit model.', references: ['Type inference', 'unknown', 'any'], quizQuestion: 'Why is inference useful?', quizAnswer: 'It provides accurate types without repeating obvious declarations.', quizOptions: ['It provides accurate types without repeating obvious declarations.', 'It disables checking.', 'It converts TypeScript to SQL.'], quizExplanation: 'Inference reduces noise while preserving compiler information.' }),
    createCurriculumTopic({ id: 'typescript-functions', title: 'Typed Functions and Parameters', summary: 'Describe function inputs, return values, callbacks, and optional defaults.', level: 'Beginner', duration: '1h 45m', focus: ['Parameters', 'Return types', 'Callbacks'], exercise: 'Type a lesson filter', starterCode: 'function byLevel(level: string = "Beginner"): string { return level; }', expectedResult: 'Callers get feedback when they pass the wrong shape or use the wrong return value.', challenge: 'Type a callback that receives a lesson and returns a boolean.', references: ['Function types', 'Optional parameters', 'Default parameters'], quizQuestion: 'What does a function type describe?', quizAnswer: 'The parameter types and the value the function returns.', quizOptions: ['The parameter types and the value the function returns.', 'Only the function name.', 'The network speed.'], quizExplanation: 'Function contracts make data flow easier to inspect.' }),
  ]}), ...typescriptExpansionSections],
};
