import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';

const q = (id: string, title: string, summary: string, level: 'Beginner' | 'Intermediate' | 'Advanced', focus: string[], exercise: string, starterCode: string, answer: string, options: string[], explanation: string, prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode, expectedResult: 'The query answers a stated question and handles its row and NULL behavior deliberately.', challenge: 'Add a second business question and explain how the result should be checked.', references: ['SQL standard concepts', 'Query readability', ...focus], quizQuestion: `What is the main idea in ${title}?`, quizAnswer: answer, quizOptions: options, quizExplanation: explanation, prerequisites });

export const sqlExpansionSections: TopicSection[] = [
  createSection({ id: 'sql-query-foundations', title: 'SQL Query Foundations', subtitle: 'Read and change relational data safely', topics: [
    q('sql-database-tables', 'Databases, Tables, Rows, and Columns', 'Build a mental model for relational data before writing queries.', 'Beginner', ['Tables', 'Rows and columns', 'Relationships'], 'Sketch a course schema', 'users(id, name)\nlessons(id, title)\nprogress(user_id, lesson_id)', 'The schema identifies entities, attributes, and links between records.', ['The schema identifies entities, attributes, and links between records.', 'A table is always a single value.', 'Rows cannot be related.'], 'A clear data model makes later joins and constraints easier to reason about.'),
    q('sql-distinct-null', 'DISTINCT and NULL', 'Remove duplicate result values and reason about missing data correctly.', 'Beginner', ['DISTINCT', 'IS NULL', 'Three-valued logic'], 'Find unique categories', 'SELECT DISTINCT category\nFROM lessons\nWHERE archived_at IS NULL;', 'The query returns unique active categories and does not compare NULL with equals.', ['The query returns unique active categories and does not compare NULL with equals.', 'NULL equals every value.', 'DISTINCT changes stored rows.'], 'NULL represents an unknown or absent value, so IS NULL is the correct test.'),
    q('sql-aggregates', 'Aggregate Functions', 'Use COUNT, SUM, AVG, MIN, and MAX to summarize rows.', 'Beginner', ['COUNT', 'SUM and AVG', 'NULL behavior'], 'Summarize lesson minutes', 'SELECT COUNT(*), AVG(minutes)\nFROM lessons;', 'The result gives a compact summary while the chosen count matches the question.', ['The result gives a compact summary while the chosen count matches the question.', 'Aggregates always return every row.', 'AVG sorts the table.'], 'Aggregate functions turn many rows into summary values.'),
    q('sql-safe-updates', 'Safe Data Changes and Transactions', 'Protect INSERT, UPDATE, and DELETE operations with precise conditions and checks.', 'Intermediate', ['WHERE clauses', 'Transactions', 'Rollback'], 'Correct a lesson title', 'BEGIN;\nUPDATE lessons SET title = \'New title\' WHERE id = 7;\nCOMMIT;', 'Only the intended row changes and the transaction can be rolled back before commit.', ['Only the intended row changes and the transaction can be rolled back before commit.', 'DELETE never needs a filter.', 'COMMIT undoes changes.'], 'A precise predicate and transaction boundary reduce accidental data loss.', ['sql-insert-update-delete']),
  ]}),
  createSection({ id: 'sql-relational-design', title: 'SQL Relational Design', subtitle: 'Relationships, constraints, and reusable queries', topics: [
    q('sql-join-types', 'JOIN Types and Relationship Choices', 'Choose INNER, LEFT, and other joins based on which unmatched rows matter.', 'Intermediate', ['INNER JOIN', 'LEFT JOIN', 'Join keys'], 'List users with progress', 'SELECT users.name, progress.lesson_id\nFROM users\nLEFT JOIN progress ON progress.user_id = users.id;', 'Users without progress remain in the report because the left table is preserved.', ['Users without progress remain in the report because the left table is preserved.', 'LEFT JOIN always removes unmatched users.', 'JOINs combine unrelated columns randomly.'], 'Join type changes which rows survive the combination.'),
    q('sql-constraints-keys', 'Constraints and Primary Foreign Keys', 'Use database rules to protect identity, uniqueness, and valid relationships.', 'Intermediate', ['Primary keys', 'Foreign keys', 'NOT NULL and UNIQUE'], 'Design enrollment tables', 'CREATE TABLE enrollments (\n  user_id INT NOT NULL,\n  course_id INT NOT NULL,\n  UNIQUE(user_id, course_id)\n);', 'The database rejects duplicate enrollment pairs and incomplete required values.', ['The database rejects duplicate enrollment pairs and incomplete required values.', 'Constraints only format text.', 'Foreign keys create UI buttons.'], 'Constraints move important invariants close to the data.'),
    q('sql-normalization', 'Relationships and Normalization', 'Reduce update anomalies by separating facts into focused related tables.', 'Intermediate', ['One-to-many', 'Many-to-many', 'Normalization'], 'Normalize course tags', 'courses(id, title)\ntags(id, name)\ncourse_tags(course_id, tag_id)', 'Repeated tag values live once and the link table models many-to-many membership.', ['Repeated tag values live once and the link table models many-to-many membership.', 'Normalization duplicates every fact.', 'One table should hold every concept.'], 'Normalization helps data stay consistent as it changes.'),
    q('sql-case-views-ctes', 'CASE, Views, and Common Table Expressions', 'Name reusable query steps and turn raw values into useful report categories.', 'Intermediate', ['CASE', 'Views', 'CTEs'], 'Create a progress report', 'WITH totals AS (SELECT user_id, COUNT(*) AS total FROM progress GROUP BY user_id)\nSELECT user_id, CASE WHEN total > 5 THEN \'active\' ELSE \'new\' END\nFROM totals;', 'The report separates preparation from presentation and gives each user a clear category.', ['The report separates preparation from presentation and gives each user a clear category.', 'CASE changes table definitions.', 'CTEs permanently store rows.'], 'CTEs improve readability; views can provide a reusable stored query when appropriate.'),
  ]}),
  createSection({ id: 'sql-advanced-performance', title: 'SQL Advanced Practice', subtitle: 'Windowing, plans, concurrency, and security', topics: [
    q('sql-window-functions', 'Window Functions', 'Calculate rankings and running values without collapsing detail rows.', 'Advanced', ['OVER', 'PARTITION BY', 'ROW_NUMBER'], 'Rank lesson activity', 'SELECT user_id, lesson_id,\n  ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY completed_at) AS sequence\nFROM progress;', 'Each progress row remains visible while receiving a per-user sequence number.', ['Each progress row remains visible while receiving a per-user sequence number.', 'Window functions always group into one row.', 'PARTITION deletes rows.'], 'Window functions calculate across related rows while preserving row detail.'),
    q('sql-indexes-plans', 'Indexes and Query Plans', 'Use indexes and explain plans to reduce avoidable scans after measuring a real query.', 'Advanced', ['Indexes', 'EXPLAIN', 'Selectivity'], 'Investigate a slow filter', 'EXPLAIN SELECT * FROM progress WHERE user_id = 42;\nCREATE INDEX progress_user_idx ON progress(user_id);', 'The plan is inspected before and after the index, and the tradeoff for writes is considered.', ['The plan is inspected before and after the index, and the tradeoff for writes is considered.', 'Indexes always reduce storage.', 'EXPLAIN changes rows.'], 'Indexes speed some reads but add storage and write maintenance.'),
    q('sql-acid-locking', 'ACID, Locking, and Concurrency', 'Keep multi-step changes consistent when several operations happen together.', 'Advanced', ['Atomicity', 'Isolation', 'Locks'], 'Transfer a completion record', 'BEGIN;\nUPDATE progress SET completed = 1 WHERE user_id = 2 AND lesson_id = 4;\nCOMMIT;', 'A partial operation does not become visible as a completed workflow and conflicts are handled deliberately.', ['A partial operation does not become visible as a completed workflow and conflicts are handled deliberately.', 'Transactions make failures impossible.', 'Locks are only for passwords.'], 'Transactions provide guarantees, but isolation and lock choices affect concurrency.'),
    q('sql-security-backups', 'SQL Security, Migrations, and Recovery', 'Prevent injection and plan schema changes, backups, and restoration before production incidents.', 'Advanced', ['Parameters', 'Migrations', 'Backups'], 'Review a data change', 'SELECT * FROM users WHERE email = ?;', 'User input is bound as a parameter and schema changes have a reversible migration plan.', ['User input is bound as a parameter and schema changes have a reversible migration plan.', 'String concatenation is safest.', 'Backups replace access control.'], 'Parameterized queries separate data from SQL syntax and backups limit recovery risk.'),
  ]}),
  createSection({ id: 'sql-applied-projects', title: 'SQL Applied Projects', subtitle: 'Reporting, optimization, and a business database capstone', topics: [
    q('sql-reporting-workflow', 'Reporting Workflow and Data Questions', 'Translate a product question into fields, filters, joins, and validation checks.', 'Advanced', ['Business questions', 'Report checks', 'Readable SQL'], 'Define an engagement report', 'SELECT course_id, COUNT(DISTINCT user_id) AS learners\nFROM enrollments\nGROUP BY course_id;', 'The query has a stated grain and its result can be checked against known sample rows.', ['The query has a stated grain and its result can be checked against known sample rows.', 'Reports need no definition.', 'GROUP BY answers every question.'], 'Naming the question and row grain prevents plausible but incorrect reports.'),
    q('sql-optimization-task', 'Query Optimization Task', 'Improve a slow report by checking joins, filters, indexes, and the query plan.', 'Advanced', ['Bottlenecks', 'Indexes', 'Plan comparison'], 'Optimize a completion report', 'EXPLAIN SELECT u.id, COUNT(p.lesson_id)\nFROM users u LEFT JOIN progress p ON p.user_id = u.id\nGROUP BY u.id;', 'The optimized query produces the same correct result with a measured improvement.', ['The optimized query produces the same correct result with a measured improvement.', 'Optimization means deleting rows.', 'A faster query can return wrong data.'], 'Correctness is required before performance comparisons matter.'),
    q('sql-migrations-design', 'Schema Migration Planning', 'Change tables safely while keeping old and new application versions compatible during rollout.', 'Advanced', ['Expand and contract', 'Backfills', 'Rollback'], 'Add a required field', 'ALTER TABLE lessons ADD COLUMN slug TEXT;\n-- backfill, validate, then add stricter constraints', 'The change can roll out in stages and existing rows are accounted for.', ['The change can roll out in stages and existing rows are accounted for.', 'Migrations should delete old data first.', 'A schema change needs no deployment plan.'], 'Staged migrations reduce downtime and compatibility surprises.'),
    q('sql-business-capstone', 'Small Business Database Capstone', 'Design tables and reports for a small course business using constraints, joins, CTEs, and indexes.', 'Advanced', ['Schema design', 'Reports', 'Performance review'], 'Build a learning business database', 'CREATE TABLE courses (id INT PRIMARY KEY, title TEXT NOT NULL);\nCREATE TABLE enrollments (user_id INT, course_id INT);', 'The capstone includes a coherent schema, sample reports, safe changes, and a short optimization review.', ['The capstone includes a coherent schema, sample reports, safe changes, and a short optimization review.', 'A capstone is only a table screenshot.', 'Reports do not need test data.'], 'A database project proves design and query decisions together.', ['sql-reporting-workflow', 'sql-indexes-plans']),
  ]}),
];
