import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
const q = (id: string, title: string, summary: string, level: 'Beginner'|'Intermediate'|'Advanced', focus: string[], exercise: string, answer: string, explanation: string, prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode: '/* implement the focused C concept */\nint result = 0;', expectedResult: 'The program demonstrates the concept with explicit ownership and a checked result.', challenge: 'Add a boundary case and compile with warnings enabled.', references: ['C standard library', ...focus], quizQuestion: `Why does ${title} matter?`, quizAnswer: answer, quizOptions: [answer, 'It removes the need for memory checks.', 'It only changes terminal colors.'], quizExplanation: explanation, prerequisites });
export const cExpansionSections: TopicSection[] = [
 createSection({ id: 'c-memory-data', title: 'C Memory and Data', subtitle: 'Use pointers, structures, allocation, and files safely', topics: [
  q('c-pointers', 'Pointers and Addresses', 'Read and write through addresses while keeping pointer targets valid.', 'Intermediate', ['& and *', 'Addresses', 'Null pointers'], 'Update a value through a pointer', 'A pointer stores an address and dereferencing accesses the pointed-to object.', 'Pointer operations require a valid target and a clear ownership story.', ['c-arrays-strings-scope']),
  q('c-pointer-arrays', 'Pointer Arithmetic and Arrays', 'Relate pointers to contiguous arrays without crossing their bounds.', 'Intermediate', ['Pointer arithmetic', 'Bounds', 'Array decay'], 'Walk an integer array', 'Pointer increments move by the pointed-to type within the same array.', 'Pointer arithmetic is only defined within the relevant array object.'),
  q('c-structs-unions-enums', 'Structures, Unions, Enums, and typedef', 'Create named data models and choose whether fields share or occupy separate storage.', 'Intermediate', ['struct', 'union', 'enum'], 'Model an address entry', 'A struct stores fields together while a union reuses the same storage for alternatives.', 'Choose data representation based on the invariant you need.'),
  q('c-dynamic-memory', 'Dynamic Memory and Ownership', 'Allocate, resize, and release heap memory without leaks or use-after-free.', 'Intermediate', ['malloc', 'realloc', 'free'], 'Grow a name list', 'Every successful allocation has one clear release path and capacity is tracked.', 'Ownership and failure handling are part of the allocation contract.', ['c-pointers']),
  q('c-file-cli', 'File Handling and Command-Line Arguments', 'Read persistent data and make terminal tools respond to explicit arguments.', 'Intermediate', ['fopen', 'argv', 'Parsing'], 'Build a file counter', 'The program checks file operations and handles missing or malformed arguments.', 'C APIs report failure through return values that must be checked.'),
  q('c-function-pointers', 'Function Pointers and Callbacks', 'Pass behavior into reusable algorithms while keeping signatures compatible.', 'Intermediate', ['Function pointers', 'Callbacks', 'qsort'], 'Sort with a comparator', 'A callback lets an algorithm call caller-provided behavior through a matching signature.', 'Function pointer types are contracts and mismatches are dangerous.'),
  q('c-preprocessor-modules', 'Headers, Macros, and Modular C Projects', 'Separate declarations and definitions while keeping macros limited and safe.', 'Intermediate', ['Headers', 'Include guards', 'Macros'], 'Split a module', 'Headers expose interfaces and source files hold implementation details.', 'Prefer functions and typed constants over macros when possible.'),
 ]}),
 createSection({ id: 'c-systems-safety', title: 'C Systems Practice', subtitle: 'Reason about layout, debugging, and common failure modes', topics: [
  q('c-memory-layout', 'Memory Layout: Stack, Heap, and Globals', 'Understand where common objects live and how lifetime affects validity.', 'Advanced', ['Stack', 'Heap', 'Lifetime'], 'Trace object lifetimes', 'A pointer becomes invalid when its target lifetime ends even if the address remains.', 'Lifetime reasoning prevents dangling-pointer bugs.'),
  q('c-undefined-behavior', 'Undefined Behavior and Const Correctness', 'Recognize operations the language does not define and protect read-only inputs.', 'Advanced', ['UB', 'const', 'Warnings'], 'Audit an unsafe loop', 'Undefined behavior is not a predictable error mode and must be removed rather than tested around.', 'Compiler warnings and clear const contracts expose risky assumptions.'),
  q('c-bitwise-alignment', 'Bitwise Operations and Struct Layout', 'Use masks deliberately and understand padding and alignment tradeoffs.', 'Advanced', ['Masks', 'Shifts', 'Alignment'], 'Pack feature flags', 'Bitwise operations can represent flags, while layout may include padding between fields.', 'Representation choices need portability and readability checks.'),
  q('c-debugging-gdb', 'Debugging with Warnings and gdb', 'Narrow crashes with compiler diagnostics, breakpoints, and variable inspection.', 'Advanced', ['Warnings', 'Breakpoints', 'Backtraces'], 'Investigate a crash', 'A reproducible failure and a backtrace provide evidence for a focused fix.', 'Debuggers show runtime state but do not replace reasoning.'),
  q('c-valgrind-security', 'Memory Debugging and Buffer Overflow Awareness', 'Find leaks and invalid access while treating external input as hostile.', 'Advanced', ['Valgrind', 'Bounds', 'Input safety'], 'Harden a line reader', 'Bounds checks and memory tools reduce the risk of corruption and data exposure.', 'Memory safety is a security concern as well as a correctness concern.'),
  q('c-data-structures', 'Linked Lists, Stacks, and Queues', 'Implement core structures while documenting ownership and complexity.', 'Advanced', ['Linked list', 'Stack', 'Queue'], 'Build a task queue', 'Each node has a clear link and release path, and operations state their complexity.', 'Data structures combine pointer correctness with algorithmic tradeoffs.'),
  q('c-make-performance', 'Make, Build Flags, and Performance Basics', 'Make builds repeatable and measure before changing low-level code.', 'Advanced', ['Makefile', 'Optimization flags', 'Profiling'], 'Create a modular build', 'The build recompiles only changed modules and performance claims are measured.', 'Build automation and measurement keep systems work reliable.'),
 ]}),
 createSection({ id: 'c-capstone', title: 'C Applied Project', subtitle: 'Build a modular terminal application', topics: [
  q('c-address-book-capstone', 'C Address Book Capstone', 'Build a terminal app with structs, pointers, files, command arguments, and modular source files.', 'Advanced', ['Capstone', 'Persistence', 'Ownership'], 'Build an address book', 'The capstone validates input, persists records, checks allocation failures, and separates modules.', 'Integration proves that memory, files, data modeling, and build structure work together.', ['c-dynamic-memory', 'c-file-cli']),
 ]}),
 createSection({ id: 'c-applied-practice', title: 'C Applied Practice', subtitle: 'Reinforce systems thinking with focused exercises', topics: [
  q('c-input-validation', 'Input Validation and Error Contracts', 'Treat terminal and file input as untrusted and return explicit failure results.', 'Intermediate', ['Validation', 'errno', 'Contracts'], 'Harden a command parser', 'A parser validates lengths and values before they reach memory or business logic.', 'Explicit error contracts keep callers from guessing what failed.'),
  q('c-memory-testing', 'Testing Memory Ownership', 'Test allocation failure paths and ownership transitions instead of only happy paths.', 'Advanced', ['Test seams', 'Ownership', 'Failure paths'], 'Test a growable buffer', 'Tests exercise normal, empty, full, and allocation-failure behavior.', 'Memory tests are strongest when ownership rules are written down first.'),
  q('c-portability', 'Portable C and Standard Library Choices', 'Avoid assumptions about integer size, layout, and platform-specific behavior.', 'Advanced', ['stdint.h', 'Portability', 'Standards'], 'Review a portable type', 'Explicit-width types and checked conversions make platform assumptions visible.', 'Portable code documents where the platform matters.'),
  q('c-modular-data-structure', 'Modular Data Structure Design', 'Expose a small header interface around an opaque data structure.', 'Advanced', ['Opaque pointers', 'API design', 'Ownership'], 'Hide a list implementation', 'Callers use operations without depending on private node layout.', 'Opaque boundaries reduce coupling and preserve implementation freedom.'),
  q('c-terminal-capstone', 'C Terminal Records Capstone', 'Extend a file-backed terminal app with search, update, validation, and modular tests.', 'Advanced', ['Search', 'Updates', 'Modules'], 'Build a records tool', 'The application keeps records consistent while checking all file and memory failures.', 'A second capstone exercise reinforces the full C workflow.'),
  q('c-systems-review', 'C Systems Review', 'Audit a small program for undefined behavior, leaks, bounds errors, and build warnings.', 'Advanced', ['Audit', 'Warnings', 'Security'], 'Perform a safety review', 'The review produces a prioritized list of correctness and security fixes.', 'Systems quality depends on disciplined review as well as implementation.'),
 ]}),
];
