import { LanguageRoadmap } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
import { cExpansionSections } from './expansion';
export const cRoadmap: LanguageRoadmap = { key: 'c', title: 'C Learning Module', shortTitle: 'C', subtitle: 'C syntax, pointers, memory, files, and systems fundamentals', description: 'Learn C from compilation and control flow through pointers, memory ownership, data structures, and safe modular programs.', icon: 'code-outline', color: '#4B8BBE', totalHours: '40h', focusAreas: ['Pointers', 'Memory', 'Files', 'Systems'], recommendedProject: 'Build a terminal address-book application with structures, files, pointers, and modular compilation.', sections: [createSection({ id: 'c-foundations', title: 'C Foundations', subtitle: 'Compile programs and work with core values', topics: [
 createCurriculumTopic({ id: 'c-program-compile', title: 'C Program Structure and Compilation', summary: 'Understand source files, headers, object files, linking, and the executable.', level: 'Beginner', duration: '1h 30m', focus: ['main', 'Compiler', 'Linker'], exercise: 'Compile Hello C', starterCode: '#include <stdio.h>\nint main(void) { puts("Hello"); return 0; }', expectedResult: 'The program compiles with warnings enabled and returns a successful status.', challenge: 'Separate the greeting into a helper function.', references: ['gcc or clang', 'main', 'Compilation'], quizQuestion: 'What does a linker do?', quizAnswer: 'It combines compiled objects and libraries into an executable.', quizOptions: ['It combines compiled objects and libraries into an executable.', 'It formats source code only.', 'It runs SQL migrations.'], quizExplanation: 'Compilation and linking are distinct build stages.' }),
 createCurriculumTopic({ id: 'c-types-variables', title: 'Variables, Data Types, and Operators', summary: 'Use integer, floating, character, and boolean-like values intentionally.', level: 'Beginner', duration: '1h 35m', focus: ['int and char', 'Conversions', 'Operators'], exercise: 'Build a score calculator', starterCode: 'int score = 80;\nint passed = score >= 50;\nprintf("%d\\n", passed);', expectedResult: 'Expressions use compatible types and the result is printed with the correct format.', challenge: 'Handle a decimal average without integer truncation.', references: ['C types', 'Operators', 'printf'], quizQuestion: 'Why do C format specifiers matter?', quizAnswer: 'They tell input and output functions how to interpret the value representation.', quizOptions: ['They tell input and output functions how to interpret the value representation.', 'They allocate every pointer.', 'They replace headers.'], quizExplanation: 'A mismatched format can cause incorrect output or undefined behavior.' }),
 createCurriculumTopic({ id: 'c-control-functions', title: 'Input, Conditions, Loops, and Functions', summary: 'Build procedural programs from decisions, repetition, and reusable functions.', level: 'Beginner', duration: '1h 50m', focus: ['scanf', 'Control flow', 'Functions'], exercise: 'Create a menu loop', starterCode: 'for (int option = 1; option <= 3; option++) { printf("%d\\n", option); }', expectedResult: 'The menu repeats predictably and each operation is separated into a function.', challenge: 'Reject an option outside the allowed range.', references: ['if', 'for', 'while', 'Functions'], quizQuestion: 'Why use a function?', quizAnswer: 'To give reusable behavior a focused name and parameter contract.', quizOptions: ['To give reusable behavior a focused name and parameter contract.', 'To avoid compiling.', 'To make all data global.'], quizExplanation: 'Functions make procedural code easier to test and organize.' }),
 createCurriculumTopic({ id: 'c-arrays-strings-scope', title: 'Arrays, Strings, and Scope', summary: 'Store contiguous values and understand C strings as character arrays.', level: 'Beginner', duration: '1h 50m', focus: ['Arrays', 'NUL terminator', 'Scope'], exercise: 'Count characters', starterCode: 'char word[] = "code";\nint length = 0;\nwhile (word[length] != \'\\0\') length++;', expectedResult: 'The program respects the string terminator and keeps variables at the smallest useful scope.', challenge: 'Count vowels without reading past the terminator.', references: ['Arrays', 'String library', 'Scope'], quizQuestion: 'How does a C string end?', quizAnswer: 'With a NUL character.', quizOptions: ['With a NUL character.', 'With a Java object.', 'With a SQL semicolon only.'], quizExplanation: 'C strings are arrays conventionally terminated by \\0.' }),
 ]}), ...cExpansionSections] };
