import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
const q = (id: string, title: string, summary: string, level: 'Beginner'|'Intermediate'|'Advanced', prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus: ['Rust design', 'Safe exercise', 'Explicit errors'], exercise: `Build a local ${title.toLowerCase()} example`, starterCode: 'fn main() {\n    let value = 1;\n    println!("{}", value);\n}', expectedResult: `The example demonstrates ${title.toLowerCase()} with a checked result.`, challenge: 'Add a boundary case and a focused test.', references: ['Rust standard library', title], quizQuestion: `Why is ${title} useful?`, quizAnswer: 'It gives a clear Rust pattern for the problem it addresses.', quizOptions: ['It gives a clear Rust pattern for the problem it addresses.', 'It only changes colors.', 'It makes every failure impossible.'], quizExplanation: 'Good Rust code makes ownership, errors, and data flow explicit.', prerequisites });
export const rustExpansionSections: TopicSection[] = [
 createSection({ id: 'rust-data-errors', title: 'Rust Data and Errors', subtitle: 'Model data, collections, and recoverable failures', topics: [
  q('rust-slices-strings', 'Slices and Strings', 'Use borrowed views and owned strings with clear lifetime relationships.', 'Beginner', ['rust-ownership-borrowing']), q('rust-structs-enums-match', 'Structs, Enums, and match', 'Model data and handle every meaningful variant explicitly.', 'Beginner'), q('rust-option-result', 'Option, Result, and Error Handling', 'Represent absence and failure without sentinel values.', 'Intermediate'), q('rust-modules-crates', 'Modules, Packages, and Crates', 'Organize a Rust project into reusable visibility boundaries.', 'Intermediate'), q('rust-collections', 'Vectors and HashMap', 'Choose standard collections and handle ownership while iterating.', 'Intermediate'), q('rust-generics-traits', 'Generics and Traits', 'Reuse algorithms while expressing required capabilities.', 'Intermediate'), q('rust-lifetimes', 'Lifetimes', 'Describe relationships between borrowed inputs and outputs.', 'Intermediate', ['rust-ownership-borrowing']),
 ]}),
 createSection({ id: 'rust-abstractions', title: 'Rust Abstractions', subtitle: 'Use closures, iterators, and smart pointers', topics: [
  q('rust-closures-iterators', 'Closures and Iterators', 'Compose transformations without unnecessary intermediate collections.', 'Intermediate'), q('rust-smart-pointers', 'Smart Pointer Overview', 'Understand ownership tools beyond ordinary references.', 'Intermediate'), q('rust-box', 'Box and Heap Ownership', 'Place values on the heap when recursive or sized ownership requires it.', 'Advanced'), q('rust-rc-arc', 'Rc and Arc', 'Choose shared ownership for single-threaded or concurrent contexts.', 'Advanced'), q('rust-refcell-interior', 'RefCell and Interior Mutability', 'Use runtime borrow checking only when the design genuinely needs it.', 'Advanced'), q('rust-traits-depth', 'Traits in Depth and Advanced Lifetimes', 'Combine bounds, associated behavior, and lifetime relationships carefully.', 'Advanced'), q('rust-unsafe-ffi', 'Unsafe Rust and FFI Concepts', 'Understand the boundary where manual invariants and foreign APIs begin.', 'Advanced'),
 ]}),
 createSection({ id: 'rust-concurrency-quality', title: 'Rust Concurrency and Quality', subtitle: 'Build reliable, tested, and organized programs', topics: [
  q('rust-threads-message', 'Threads and Message Passing', 'Move owned values between threads through channels.', 'Advanced'), q('rust-shared-concurrency', 'Shared-State Concurrency and Send/Sync', 'Reason about safe sharing and thread-safety marker traits.', 'Advanced'), q('rust-async', 'Async Concepts', 'Understand futures, runtimes, and cancellation at a conceptual level.', 'Advanced'), q('rust-testing-docs', 'Testing and Documentation Tests', 'Verify behavior and keep examples executable as documentation.', 'Intermediate'), q('rust-performance-memory', 'Performance and Memory Safety', 'Measure allocations and preserve safety while optimizing.', 'Advanced'), q('rust-cargo-workspaces', 'Cargo Workspaces and Project Organization', 'Split larger Rust projects into coherent packages.', 'Advanced'), q('rust-cli-capstone', 'Rust CLI/Service Capstone', 'Build a tested project using ownership, traits, modules, errors, and safe concurrency.', 'Advanced', ['rust-option-result', 'rust-generics-traits', 'rust-testing-docs']),
 ]}),
 createSection({ id: 'rust-applied-practice', title: 'Rust Applied Practice', subtitle: 'Reinforce explicit error design', topics: [
  q('rust-error-design', 'Result-Based Parser Exercise', 'Design a parser that returns useful errors instead of panicking on bad input.', 'Intermediate'),
 ]}),
];
