import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
const q = (id: string, title: string, summary: string, level: 'Beginner'|'Intermediate'|'Advanced', focus: string[], exercise: string, answer: string, explanation: string, prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode: 'class Example {\n  // implement the focused concept here\n}', expectedResult: 'The example is organized around the stated Java concept and can be tested with normal and edge inputs.', challenge: 'Add a focused test or validation case.', references: ['Java API', ...focus], quizQuestion: `Why does ${title} matter?`, quizAnswer: answer, quizOptions: [answer, 'It removes the need for all classes.', 'It only changes console colors.'], quizExplanation: explanation, prerequisites });
export const javaExpansionSections: TopicSection[] = [
 createSection({ id: 'java-oop-packages', title: 'Java Object Design', subtitle: 'Build maintainable object models and collections', topics: [
  q('java-encapsulation', 'Encapsulation and Access Modifiers', 'Protect object invariants with private state and deliberate public methods.', 'Intermediate', ['private', 'public', 'Getters and methods'], 'Protect a balance object', 'Private state with validated methods protects an object invariant.', 'Encapsulation keeps invalid state changes behind a controlled interface.', ['java-methods-classes']),
  q('java-inheritance-polymorphism', 'Inheritance and Polymorphism', 'Use shared contracts and substitutions without forcing unrelated classes into one hierarchy.', 'Intermediate', ['extends', 'Override', 'Polymorphism'], 'Model notification types', 'A base contract lets callers use different implementations through one reference.', 'Polymorphism reduces caller branching when the abstraction is genuinely shared.', ['java-encapsulation']),
  q('java-abstraction-interfaces', 'Abstraction and Interfaces', 'Define capabilities that multiple classes can implement.', 'Intermediate', ['Interfaces', 'Abstract classes', 'Contracts'], 'Create a storage interface', 'An interface describes what a service does without fixing its implementation.', 'Interfaces support substitution and focused tests.'),
  q('java-packages-enums', 'Packages, Enums, and Project Boundaries', 'Organize classes and represent finite states clearly.', 'Intermediate', ['Packages', 'Enums', 'Visibility'], 'Organize order states', 'Packages separate responsibilities and enums restrict status values.', 'Named boundaries make larger Java projects easier to navigate.'),
  q('java-collections-generics', 'Collections and Generics', 'Use List, Set, Map, and type parameters to manage data safely.', 'Intermediate', ['List', 'Set and Map', 'Generics'], 'Index tasks by ID', 'Generics preserve the element type while collections express access needs.', 'Typed collections prevent many casts and document intent.'),
  q('java-exceptions-files', 'Exceptions and File Handling', 'Recover from expected failures and persist simple local data.', 'Intermediate', ['try/catch', 'Path', 'Checked exceptions'], 'Read a task file', 'Specific exceptions and try-with-resources make file behavior explicit.', 'Error handling should preserve useful context and close resources.'),
  q('java-datetime-lambda', 'Dates, Lambdas, and Optional', 'Handle time values and small transformations without ambiguous null behavior.', 'Intermediate', ['java.time', 'Lambdas', 'Optional'], 'Filter due tasks', 'Modern time types and Optional make absence and transformations explicit.', 'Optional is a return-value tool, not a replacement for every field.'),
  q('java-streams', 'Streams and Collection Pipelines', 'Transform and aggregate collections through readable stream operations.', 'Intermediate', ['map', 'filter', 'collect'], 'Summarize completed tasks', 'A stream pipeline expresses a source, transformations, and a terminal result.', 'Streams can clarify data flow when the pipeline stays readable.', ['java-collections-generics']),
 ]}),
 createSection({ id: 'java-runtime', title: 'Java Runtime and Production', subtitle: 'Concurrency, JVM behavior, persistence, and quality', topics: [
  q('java-threads-executors', 'Threads and Executors', 'Run independent work with explicit lifecycle and bounded execution.', 'Advanced', ['Thread', 'ExecutorService', 'Future'], 'Schedule report work', 'Executors manage worker lifecycle more safely than creating unbounded threads.', 'A bounded executor makes concurrency and shutdown responsibilities visible.'),
  q('java-synchronization', 'Synchronization and Concurrent Data', 'Protect shared mutable state and choose safer concurrent collections.', 'Advanced', ['Locks', 'synchronized', 'Atomicity'], 'Protect a counter', 'Synchronization prevents conflicting updates when shared state must change together.', 'The smallest correct critical section reduces contention.'),
  q('java-jvm-memory-gc', 'JVM Memory and Garbage Collection', 'Understand stack frames, heap objects, references, and garbage collection basics.', 'Advanced', ['Stack and heap', 'References', 'GC'], 'Investigate object growth', 'The JVM reclaims unreachable objects, but retaining references can still grow memory.', 'Garbage collection does not fix leaks caused by reachable objects.'),
  q('java-records-sealed', 'Records and Sealed Classes', 'Use modern Java constructs for immutable data and closed hierarchies.', 'Advanced', ['Records', 'Sealed', 'Pattern thinking'], 'Model an API result', 'Records reduce boilerplate for data carriers and sealed types constrain variants.', 'Modern constructs make intent explicit when their constraints fit.'),
  q('java-reflection-annotations', 'Reflection and Annotations', 'Understand metadata-driven frameworks without hiding the runtime costs.', 'Advanced', ['Annotations', 'Reflection', 'Metadata'], 'Inspect a class', 'Annotations describe metadata and reflection reads it at runtime.', 'Reflection is flexible but should remain behind clear boundaries.'),
  q('java-testing-logging', 'Testing and Logging', 'Verify behavior and diagnose failures without exposing sensitive data.', 'Advanced', ['Unit tests', 'Integration tests', 'Logging'], 'Test a service', 'Tests assert behavior while structured logs explain operational context.', 'Good tests and logs support different feedback loops.'),
  q('java-jdbc-security', 'JDBC, Serialization, and Security Basics', 'Connect persistence concepts with parameterized queries and safe data handling.', 'Advanced', ['JDBC', 'Parameters', 'Serialization'], 'Design a repository', 'Parameterized database operations keep values separate from SQL syntax.', 'Serialization and persistence boundaries must validate untrusted data.'),
  q('java-build-performance', 'Maven, Gradle, and Performance', 'Make builds repeatable and measure Java behavior before optimizing.', 'Advanced', ['Build tools', 'Profiling', 'Dependencies'], 'Plan a build', 'Build tools standardize dependencies, tests, packaging, and repeatable commands.', 'Measurement should guide performance changes.'),
 ]}),
 createSection({ id: 'java-capstone', title: 'Java Applied Project', subtitle: 'Combine OOP, collections, persistence, and tests', topics: [
  q('java-cli-capstone', 'Java CLI Task Service Capstone', 'Build a tested console application using OOP, collections, file persistence, and clear project structure.', 'Advanced', ['CLI design', 'OOP integration', 'Testing'], 'Build a task service', 'A capstone combines models, services, collections, persistence decisions, and tests.', 'Integration is the point of a capstone: each boundary should remain understandable.', ['java-streams', 'java-testing-logging']),
 ]}),
 createSection({ id: 'java-applied-practice', title: 'Java Applied Practice', subtitle: 'Turn core Java skills into maintainable services', topics: [
  q('java-project-structure', 'Java Project Structure and Build Layout', 'Separate packages, application code, tests, resources, and build output.', 'Intermediate', ['src layout', 'Packages', 'Build output'], 'Plan a service layout', 'A predictable project layout keeps production code, tests, and resources easy to find.', 'Clear boundaries make builds and reviews more reliable.'),
  q('java-serialization', 'Serialization and Data Formats', 'Compare object serialization with explicit portable formats at data boundaries.', 'Advanced', ['JSON', 'Compatibility', 'Validation'], 'Design a saved record', 'Explicit formats make stored data easier to inspect and migrate.', 'Persistence formats are contracts that need versioning and validation.'),
  q('java-concurrency-review', 'Concurrency Review and Safe Shutdown', 'Combine executors, cancellation, and resource shutdown into a controlled workflow.', 'Advanced', ['Cancellation', 'Shutdown', 'Executors'], 'Stop a worker pool', 'A service stops accepting work, cancels or drains tasks, and closes resources deliberately.', 'Lifecycle behavior is part of concurrent correctness.'),
  q('java-backend-capstone', 'Java Backend Service Capstone', 'Plan a small backend-style service with models, collections, persistence, logs, and tests.', 'Advanced', ['Service design', 'Persistence', 'Tests'], 'Build a course service', 'The service exposes clear operations and tests both successful and failed requests.', 'A backend capstone connects language features to a useful application boundary.'),
 ]}),
];
