import { LanguageRoadmap } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
import { javaExpansionSections } from './expansion';

export const javaRoadmap: LanguageRoadmap = { key: 'java', title: 'Java Learning Module', shortTitle: 'Java', subtitle: 'Object-oriented Java, collections, concurrency, and backend foundations', description: 'Learn Java from JDK fundamentals through object-oriented design, collections, concurrency, persistence, and testing.', icon: 'code-outline', color: '#E76F00', totalHours: '44h', focusAreas: ['Syntax', 'OOP', 'Collections', 'JVM'], recommendedProject: 'Build a tested CLI task service with object-oriented models, collections, and persistence planning.', sections: [createSection({ id: 'java-foundations', title: 'Java Foundations', subtitle: 'Run Java and write clear first programs', topics: [
  createCurriculumTopic({ id: 'java-setup-jdk', title: 'JDK, JVM, and JRE Setup', summary: 'Understand the Java toolchain and compile a first program.', level: 'Beginner', duration: '1h 25m', focus: ['JDK', 'JVM', 'javac and java'], exercise: 'Run a Hello Java program', starterCode: 'public class Main { public static void main(String[] args) { System.out.println("Hello"); } }', expectedResult: 'The source compiles to bytecode and runs on the JVM.', challenge: 'Print the Java version and a second line.', references: ['JDK', 'JVM'], quizQuestion: 'What executes Java bytecode?', quizAnswer: 'The Java Virtual Machine.', quizOptions: ['The Java Virtual Machine.', 'Only the text editor.', 'A SQL database.'], quizExplanation: 'The JVM provides the runtime that executes compiled bytecode.' }),
  createCurriculumTopic({ id: 'java-syntax-types', title: 'Java Syntax, Variables, and Types', summary: 'Use statements, primitive values, references, and explicit declarations.', level: 'Beginner', duration: '1h 40m', focus: ['Primitives', 'References', 'Declarations'], exercise: 'Create a student record', starterCode: 'int lessons = 3;\nString name = "Ada";\nboolean active = true;', expectedResult: 'Variables have intentional types and the program compiles without unsafe conversions.', challenge: 'Convert a numeric string and handle invalid input.', references: ['Primitive types', 'Reference types'], quizQuestion: 'What is a reference variable?', quizAnswer: 'A variable that refers to an object rather than holding the object value directly.', quizOptions: ['A variable that refers to an object rather than holding the object value directly.', 'A CPU register only.', 'A compiled SQL query.'], quizExplanation: 'Reference semantics matter when objects are shared or null.' }),
  createCurriculumTopic({ id: 'java-control-input', title: 'Operators, Input, Conditions, and Loops', summary: 'Build interactive console programs with decisions and repetition.', level: 'Beginner', duration: '1h 45m', focus: ['Operators', 'Scanner', 'Loops'], exercise: 'Build a marks analyzer', starterCode: 'for (int score : new int[] {80, 65}) {\n  System.out.println(score >= 70 ? "Pass" : "Retry");\n}', expectedResult: 'Each input follows a clear branch and repeated work is handled by a loop.', challenge: 'Read scores until the user enters a sentinel value.', references: ['Scanner', 'if', 'for'], quizQuestion: 'What does a loop provide?', quizAnswer: 'A way to repeat work while a condition or collection requires it.', quizOptions: ['A way to repeat work while a condition or collection requires it.', 'Automatic persistence.', 'A replacement for types.'], quizExplanation: 'Loops express repeated processing.' }),
  createCurriculumTopic({ id: 'java-methods-classes', title: 'Methods, Classes, Objects, and Constructors', summary: 'Model behavior and data with reusable Java objects.', level: 'Beginner', duration: '2h', focus: ['Methods', 'Objects', 'Constructors'], exercise: 'Model a Task class', starterCode: 'class Task {\n  String title;\n  Task(String title) { this.title = title; }\n}', expectedResult: 'Objects are created through a clear constructor and methods represent behavior.', challenge: 'Add a complete method and a display method.', references: ['Classes', 'Constructors', 'this'], quizQuestion: 'What does a constructor do?', quizAnswer: 'It initializes a new object when it is created.', quizOptions: ['It initializes a new object when it is created.', 'It starts the JVM.', 'It deletes a class.'], quizExplanation: 'Constructors establish initial object state.' }),
]}), ...javaExpansionSections] };
