import type { LanguageKey, TopicLevel } from '../content/types';
import { getLanguageTopicsMetadata } from '../content/topicIndex';

export type CompletionState = 'Not Started' | 'In Progress' | 'Basic Completed' | 'Intermediate Completed' | 'Advanced Completed' | 'Track Completed';
const levels: TopicLevel[] = ['Beginner', 'Intermediate', 'Advanced'];
const isOptionalGenerated = (id: string) => id.endsWith('-production-checklist') || id.endsWith('-debugging-workflow') || id.endsWith('-capstone-review');
const requiredTopics = (languageKey: LanguageKey) => getLanguageTopicsMetadata(languageKey).filter((topic) => !isOptionalGenerated(topic.id));
export const getCapstoneTopics = (languageKey: LanguageKey) => requiredTopics(languageKey).filter((topic) => topic.id.endsWith('-capstone'));
export const getLevelCompletion = (languageKey: LanguageKey, completedIds: ReadonlySet<string>) => levels.reduce<Record<TopicLevel, { completed: number; total: number; complete: boolean }>>((result, level) => { const topics = requiredTopics(languageKey).filter((topic) => topic.level === level); const completed = topics.filter((topic) => completedIds.has(topic.id)).length; result[level] = { completed, total: topics.length, complete: topics.length > 0 && completed === topics.length }; return result; }, { Beginner: { completed: 0, total: 0, complete: false }, Intermediate: { completed: 0, total: 0, complete: false }, Advanced: { completed: 0, total: 0, complete: false } });
export const getTrackCompletion = (languageKey: LanguageKey, completedIds: ReadonlySet<string>) => { const topics = requiredTopics(languageKey); const completed = topics.filter((topic) => completedIds.has(topic.id)).length; const levelsDone = getLevelCompletion(languageKey, completedIds); const capstones = getCapstoneTopics(languageKey); const capstoneComplete = capstones.length === 0 || capstones.every((topic) => completedIds.has(topic.id)); const trackComplete = topics.length > 0 && completed === topics.length && capstoneComplete; const state: CompletionState = trackComplete ? 'Track Completed' : levelsDone.Advanced.complete ? 'Advanced Completed' : levelsDone.Intermediate.complete ? 'Intermediate Completed' : levelsDone.Beginner.complete ? 'Basic Completed' : completed ? 'In Progress' : 'Not Started'; return { state, completed, total: topics.length, percent: topics.length ? Math.round(completed / topics.length * 100) : 0, levels: levelsDone, capstones, capstoneComplete, remaining: topics.filter((topic) => !completedIds.has(topic.id)) }; };
export const getCertificateEligibility = (languageKey: LanguageKey, completedIds: ReadonlySet<string>) => getTrackCompletion(languageKey, completedIds).state === 'Track Completed';
export const createLocalCertificateId = (languageKey: LanguageKey, issuedAt: string) => { let hash = 0; for (const char of `${languageKey}:${issuedAt}`) hash = (hash * 31 + char.charCodeAt(0)) >>> 0; return `LOCAL-${languageKey.toUpperCase()}-${hash.toString(36).toUpperCase()}`; };
