import { LanguageRoadmap, TopicLevel } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
type Spec = [string, string, string, TopicLevel, string[], string, string?];
const make = ([id, title, summary, level, focus, exercise, prerequisite]: Spec) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode: 'struct Lesson {\n    let title: String\n}\nlet lesson = Lesson(title: "Offline")', expectedResult: `A small offline Swift example demonstrates ${title.toLowerCase()} with an explicit result.`, challenge: `Add an edge case related to ${title.toLowerCase()} and test it.`, references: ['Swift standard library', ...focus], quizQuestion: `Why is ${title} useful?`, quizAnswer: `It makes ${title.toLowerCase()} explicit and easier to test.`, quizOptions: [`It makes ${title.toLowerCase()} explicit and easier to test.`, 'It only changes screen colors.', 'It removes all runtime failures.'], quizExplanation: 'Swift features are strongest when their data and failure behavior are explicit.', prerequisites: prerequisite ? [prerequisite] : undefined });
const basic: Spec[] = [
 ['swift-overview', 'Swift Overview and Toolchain', 'Understand Swift syntax, its native toolchain, and where Xcode fits.', 'Beginner', ['Swift', 'Compiler', 'Xcode concepts'], 'Compare a Swift source file with its compiled program flow.'],
 ['swift-setup', 'Setup, Xcode Concepts, and Playgrounds', 'Create a repeatable Swift project and use feedback from the toolchain.', 'Beginner', ['Xcode', 'Playgrounds', 'Builds'], 'Run a small offline experiment in a playground.'],
 ['swift-let-var', 'let, var, and Type Inference', 'Prefer immutable values and make mutation intentional.', 'Beginner', ['let', 'var', 'Inference'], 'Model an immutable task ID and editable task title.'],
 ['swift-types-operators', 'Types and Operators', 'Use Swift numeric, Boolean, character, and string values safely.', 'Beginner', ['Types', 'Operators', 'Conversions'], 'Calculate a completion ratio with clear types.'],
 ['swift-optionals', 'Optionals and Safe Unwrapping', 'Represent missing values without pretending absence is a valid value.', 'Beginner', ['Optionals', 'if let', 'nil'], 'Display an optional task note safely.'],
 ['swift-conditions-switch', 'Conditions and switch', 'Branch on values and use exhaustive switch cases.', 'Beginner', ['if', 'switch', 'Exhaustiveness'], 'Map task states to labels.'],
 ['swift-loops', 'Loops and Repetition', 'Use for-in, while, and repeat-while for bounded work.', 'Beginner', ['Loops', 'Ranges', 'Iteration'], 'Print unfinished task positions.'],
 ['swift-functions', 'Functions and Parameters', 'Write focused functions with labels, returns, and predictable contracts.', 'Beginner', ['Functions', 'Parameters', 'Returns'], 'Create a task filtering function.'],
 ['swift-tuples-collections', 'Tuples, Arrays, Sets, and Dictionaries', 'Choose collection shapes for ordered, unique, and keyed data.', 'Beginner', ['Tuples', 'Arrays', 'Sets', 'Dictionaries'], 'Group task tags and preserve unique values.'],
 ['swift-strings', 'Strings and Interpolation', 'Format and transform user-facing text safely.', 'Beginner', ['Strings', 'Interpolation', 'Unicode'], 'Build a readable task summary.'],
 ['swift-structs-classes', 'Structs and Classes', 'Compare value-oriented structs with reference-oriented classes.', 'Beginner', ['Structs', 'Classes', 'Values'], 'Model a task using both approaches and compare copies.'],
];
const intermediate: Spec[] = [
 ['swift-properties-methods', 'Properties and Methods', 'Attach behavior to data while keeping invariants visible.', 'Intermediate', ['Properties', 'Methods', 'Invariants'], 'Reject a blank task title in an initializer or setter.', 'swift-structs-classes'],
 ['swift-initializers', 'Initializers and Failable Construction', 'Create valid values and represent construction failure deliberately.', 'Intermediate', ['Initializers', 'Validation', 'nil'], 'Build a failable task initializer.', 'swift-optionals'],
 ['swift-inheritance', 'Inheritance and Class Design', 'Use class inheritance only where shared identity and behavior are real.', 'Intermediate', ['Inheritance', 'Overrides', 'Design'], 'Extend a base task type with a timed task.'],
 ['swift-protocols', 'Protocols and Composition', 'Define capabilities that structs and classes can implement independently.', 'Intermediate', ['Protocols', 'Conformance', 'Composition'], 'Create a protocol for sortable tasks.', 'swift-structs-classes'],
 ['swift-extensions', 'Extensions', 'Add focused behavior and protocol conformances without editing the original type.', 'Intermediate', ['Extensions', 'Reuse', 'Conformance'], 'Add a summary extension to a task collection.'],
 ['swift-enums-associated', 'Enums and Associated Values', 'Model finite states with payloads that belong to each case.', 'Intermediate', ['Enums', 'Associated values', 'State'], 'Represent task loading, success, and failure states.'],
 ['swift-errors', 'Error Handling and Result', 'Use throwing functions and Result to make failure contracts explicit.', 'Intermediate', ['Error', 'throws', 'Result'], 'Validate task commands with typed errors.', 'swift-initializers'],
 ['swift-generics', 'Generics and Constraints', 'Build reusable containers while preserving the element type.', 'Intermediate', ['Generics', 'Constraints', 'Reuse'], 'Create a typed in-memory task store.'],
 ['swift-closures-higher-order', 'Closures and Higher-Order Functions', 'Pass behavior into collection and service operations.', 'Intermediate', ['Closures', 'map', 'filter'], 'Pass a closure that selects overdue tasks.'],
 ['swift-optionals-deep', 'Advanced Optional Patterns', 'Combine optional mapping, defaults, and flattening without unsafe force unwraps.', 'Intermediate', ['map', 'flatMap', 'Defaults'], 'Read nested optional profile data safely.', 'swift-optionals'],
 ['swift-access-control', 'Access Control', 'Use private, internal, and public boundaries to protect implementation details.', 'Intermediate', ['private', 'internal', 'public'], 'Hide task storage behind a service API.', 'swift-protocols'],
 ['swift-value-reference', 'Value vs Reference Semantics', 'Predict copying, sharing, and mutation across structs and classes.', 'Intermediate', ['Semantics', 'Copying', 'Identity'], 'Demonstrate independent value copies and shared references.', 'swift-structs-classes'],
 ['swift-protocol-oriented', 'Protocol-Oriented Design', 'Compose small capabilities instead of forcing deep inheritance trees.', 'Intermediate', ['Composition', 'Defaults', 'Design'], 'Compose filtering and persistence capabilities.', 'swift-protocols'],
 ['swift-json-codable', 'Codable and JSON Models', 'Encode and decode stable data models with clear boundary handling.', 'Intermediate', ['Codable', 'JSON', 'DTOs'], 'Decode an offline task fixture.', 'swift-errors'],
];
const advanced: Spec[] = [
 ['swift-arc', 'ARC and Object Lifetime', 'Understand automatic reference counting and when objects are released.', 'Advanced', ['ARC', 'Lifetime', 'References'], 'Trace object lifetime in a small class graph.', 'swift-structs-classes'],
 ['swift-weak-unowned', 'weak and unowned References', 'Prevent retain cycles while choosing the correct lifetime guarantee.', 'Advanced', ['weak', 'unowned', 'Cycles'], 'Fix a delegate-style retain cycle.', 'swift-arc'],
 ['swift-async-await', 'async/await and Tasks', 'Structure asynchronous work and cancellation with modern Swift concurrency.', 'Advanced', ['async', 'await', 'Task'], 'Load an offline fixture asynchronously.', 'swift-errors'],
 ['swift-actors', 'Actors and Concurrency Safety', 'Protect isolated mutable state and reason about Sendable boundaries.', 'Advanced', ['Actors', 'Isolation', 'Safety'], 'Move a task cache behind an actor.', 'swift-async-await'],
 ['swift-networking', 'Networking Concepts and Codable APIs', 'Separate transport, decoding, and domain mapping at API boundaries.', 'Advanced', ['URLSession', 'Codable', 'Mapping'], 'Map a fixture as if it were an API response.', 'swift-json-codable'],
 ['swift-testing', 'Testing Swift Code', 'Test value models, errors, async functions, and protocol-based behavior.', 'Advanced', ['Tests', 'Mocks', 'Async'], 'Test a task service with a fake repository.', 'swift-protocols'],
 ['swift-performance-memory', 'Memory and Performance', 'Measure copies, allocations, and expensive work before optimizing.', 'Advanced', ['Performance', 'Memory', 'Instruments concepts'], 'Review a collection pipeline for needless work.', 'swift-value-reference'],
 ['swift-app-architecture-capstone', 'Swift Data Management Capstone', 'Build a Swift data app using protocols, Codable, async concepts, errors, and tests.', 'Advanced', ['Capstone', 'Architecture', 'Testing'], 'Plan an offline Swift task manager.', 'swift-testing'],
];
export const swiftRoadmap: LanguageRoadmap = { key: 'swift', title: 'Swift Learning Module', shortTitle: 'Swift', subtitle: 'Safe values, protocols, optionals, concurrency, and Apple-platform foundations', description: 'Learn Swift from toolchain basics through value semantics, protocols, Codable, concurrency, testing, and application architecture.', icon: 'code-outline', color: '#F05138', totalHours: '51h', focusAreas: ['Optionals', 'Protocols', 'Concurrency', 'Value Semantics'], recommendedProject: 'Build an offline Swift data-management app with Codable, protocols, async work, and tests.', sections: [createSection({ id: 'swift-foundations', title: 'Swift Foundations', subtitle: 'Build safe programs from the language core', topics: basic.map(make) }), createSection({ id: 'swift-intermediate', title: 'Swift Intermediate', subtitle: 'Compose models and behavior', topics: intermediate.map(make) }), createSection({ id: 'swift-advanced', title: 'Swift Advanced', subtitle: 'Manage lifetimes and concurrent work', topics: advanced.map(make) })] };
