import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';

const q = (id: string, title: string, summary: string, level: 'Beginner' | 'Intermediate' | 'Advanced', focus: string[], exercise: string, starterCode: string, answer: string, options: string[], explanation: string, prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode, expectedResult: 'The backend behavior is easy to exercise locally and returns an intentional result for normal and invalid input.', challenge: 'Add a focused test or log that proves the edge case is handled.', references: ['Node.js runtime', 'HTTP behavior', ...focus], quizQuestion: `What is the main idea in ${title}?`, quizAnswer: answer, quizOptions: options, quizExplanation: explanation, prerequisites });

export const nodejsExpansionSections: TopicSection[] = [
  createSection({ id: 'node-runtime-foundations', title: 'Node Runtime Foundations', subtitle: 'Async code, modules, configuration, and local resources', topics: [
    q('node-es-modules', 'CommonJS and ES Modules', 'Choose a module format consistently and understand import and export boundaries.', 'Beginner', ['require', 'import/export', 'Package type'], 'Split a utility module', 'export function toSlug(value) { return value.toLowerCase().replaceAll(" ", "-"); }', 'A route imports a focused helper using the project module convention.', ['A route imports a focused helper using the project module convention.', 'Modules only work in browsers.', 'Every file must be global.'], 'Module boundaries make dependencies visible and code easier to test.'),
    q('node-environment-config', 'Environment Variables and Configuration', 'Keep environment-specific values outside source code and validate required settings at startup.', 'Beginner', ['process.env', 'Config parsing', 'Secrets'], 'Create a config loader', 'const port = Number(process.env.PORT ?? 3000);\nif (!Number.isInteger(port)) throw new Error("Invalid PORT");', 'The app reads a safe default and fails early for invalid required configuration.', ['The app reads a safe default and fails early for invalid required configuration.', 'Secrets belong in git.', 'Environment variables are always numbers.'], 'Configuration is input and should be validated like any other input.'),
    q('node-paths-files', 'Paths and File System Safety', 'Use path utilities and deliberate encoding while avoiding unsafe user-controlled file paths.', 'Beginner', ['path.join', 'fs promises', 'Path validation'], 'Read a local lesson file', 'const filePath = path.join(dataDir, "lessons.json");\nconst text = await fs.readFile(filePath, "utf8");', 'The file is resolved under an expected directory and read asynchronously.', ['The file is resolved under an expected directory and read asynchronously.', 'String concatenation secures paths.', 'fs.readFile always returns JSON.'], 'Path resolution and encoding choices should be explicit.'),
    q('node-async-events', 'Async Programming and Events', 'Coordinate promises, timers, and event emitters without losing errors.', 'Intermediate', ['Promises', 'EventEmitter', 'Error listeners'], 'Process an import event', 'emitter.on("imported", (count) => console.log(count));\nemitter.emit("imported", 3);', 'Async work reports completion and failures through a clear contract.', ['Async work reports completion and failures through a clear contract.', 'Events automatically await listeners.', 'Promises cannot reject.'], 'Events and promises have different ownership and error-handling behavior.'),
  ]}),
  createSection({ id: 'node-api-development', title: 'Node API Development', subtitle: 'Routes, middleware, validation, auth, and API structure', topics: [
    q('node-express-routing', 'Express Routing and REST Resources', 'Map HTTP methods and resource paths to focused handlers.', 'Intermediate', ['GET and POST', 'Route params', 'REST nouns'], 'Create a lessons route', 'app.get("/lessons/:id", async (req, res) => {\n  res.json({ id: req.params.id });\n});', 'The route has a predictable resource path and returns an intentional status and body.', ['The route has a predictable resource path and returns an intentional status and body.', 'REST routes use random verbs.', 'Every request is a POST.'], 'Consistent routes help clients discover and use an API.'),
    q('node-request-middleware', 'Middleware Order and Shared Logic', 'Use middleware for cross-cutting work while preserving request flow and error behavior.', 'Intermediate', ['next', 'Order', 'Error middleware'], 'Add request timing', 'app.use((req, res, next) => {\n  const started = Date.now();\n  res.on("finish", () => console.log(Date.now() - started));\n  next();\n});', 'The middleware runs before the route and always passes control or handles its own response.', ['The middleware runs before the route and always passes control or handles its own response.', 'Middleware runs after shutdown.', 'next sends the response automatically.'], 'Middleware order affects authentication, parsing, routes, and errors.'),
    q('node-auth-passwords', 'Authentication and Password Hashing Concepts', 'Separate identity from authorization and never store plain-text passwords.', 'Intermediate', ['Sessions or tokens', 'Hashing', 'Authorization'], 'Design a login flow', 'const user = await findUser(email);\nconst valid = user && await verifyPassword(password, user.passwordHash);', 'Login verifies a stored hash and authorization checks what the identified user may do.', ['Login verifies a stored hash and authorization checks what the identified user may do.', 'Passwords should be logged.', 'Authentication grants every permission.'], 'Authentication answers who; authorization answers what they may access.'),
    q('node-pagination-upload', 'Pagination and File Uploads', 'Limit response size and treat uploaded files as untrusted input.', 'Intermediate', ['limit and offset', 'Multipart input', 'File constraints'], 'Design a paginated endpoint', 'const page = Math.max(1, Number(req.query.page ?? 1));\nconst limit = Math.min(50, Number(req.query.limit ?? 20));', 'The endpoint caps work, returns page metadata, and validates file type and size when uploads exist.', ['The endpoint caps work, returns page metadata, and validates file type and size when uploads exist.', 'Clients should receive every row.', 'File names are always safe.'], 'Bounded requests protect performance and reduce abuse.'),
  ]}),
  createSection({ id: 'node-production-engineering', title: 'Node Production Engineering', subtitle: 'Reliability, security, testing, and performance', topics: [
    q('node-streams', 'Streams and Backpressure', 'Process large data incrementally instead of buffering everything in memory.', 'Advanced', ['Readable streams', 'Pipelines', 'Backpressure'], 'Stream a local export', 'source.pipe(transform).pipe(destination);', 'The pipeline handles chunks and propagates errors without loading the whole export at once.', ['The pipeline handles chunks and propagates errors without loading the whole export at once.', 'Streams require the whole file in memory.', 'Backpressure speeds every CPU task.'], 'Backpressure lets a slower destination regulate producers.'),
    q('node-caching-rate-limit', 'Caching and Rate Limiting', 'Reduce repeated work and limit abusive request patterns with explicit expiration and keys.', 'Advanced', ['Cache keys', 'TTL', 'Request limits'], 'Cache a lesson lookup', 'const key = `lesson:${id}`;\nconst cached = await cache.get(key);', 'The cache has a bounded lifetime and rate limits protect expensive routes.', ['The cache has a bounded lifetime and rate limits protect expensive routes.', 'Caches never become stale.', 'Rate limiting is authentication.'], 'Caching trades freshness for speed; limits protect capacity.'),
    q('node-security-cors-headers', 'Security Headers and CORS', 'Restrict browser access and add defensive response headers based on the actual client contract.', 'Advanced', ['CORS origins', 'Headers', 'Threat modeling'], 'Review an API policy', 'res.setHeader("Content-Security-Policy", "default-src \'none\'");\nres.setHeader("X-Content-Type-Options", "nosniff");', 'Allowed origins and security headers are intentional rather than wildcard defaults in production.', ['Allowed origins and security headers are intentional rather than wildcard defaults in production.', 'CORS protects database passwords.', 'Wildcard access is always safest.'], 'Headers help browsers enforce boundaries but do not replace authorization.'),
    q('node-testing-logging', 'Testing, Logging, and Monitoring', 'Verify handlers at useful boundaries and produce structured signals for diagnosis.', 'Advanced', ['Unit tests', 'Integration tests', 'Structured logs'], 'Test a validation failure', 'const response = await request(app).post("/lessons").send({});\nexpect(response.status).toBe(400);', 'The test checks the public response contract and logs contain enough context without secrets.', ['The test checks the public response contract and logs contain enough context without secrets.', 'Tests should assert private locals.', 'Logs should include passwords.'], 'Operational visibility must respect privacy and the API contract.'),
  ]}),
  createSection({ id: 'node-scalable-backends', title: 'Node Applied Projects', subtitle: 'Jobs, deployment, shutdown, and a complete API capstone', topics: [
    q('node-background-jobs', 'Background Jobs and Graceful Shutdown', 'Move slow work out of request paths and stop accepting work cleanly during shutdown.', 'Advanced', ['Job queues', 'Signals', 'Drain'], 'Design an export job', 'app.post("/exports", (req, res) => {\n  queue.add({ userId: req.user.id });\n  res.status(202).json({ status: "queued" });\n});', 'The request returns quickly, the job can be retried, and shutdown drains active work.', ['The request returns quickly, the job can be retried, and shutdown drains active work.', 'Jobs must block the response.', 'SIGTERM means ignore shutdown.'], 'Async jobs improve responsiveness but require retry and lifecycle decisions.'),
    q('node-performance-process', 'Performance and Process Management', 'Measure latency, control concurrency, and choose process management strategies deliberately.', 'Advanced', ['Latency', 'Worker processes', 'Health checks'], 'Profile a slow handler', 'console.time("handler");\nawait buildReport();\nconsole.timeEnd("handler");', 'The bottleneck is measured, bounded, and monitored through a useful health signal.', ['The bottleneck is measured, bounded, and monitored through a useful health signal.', 'Performance is judged by code length.', 'Health checks should run business writes.'], 'Measurement and bounded work make performance improvements defensible.'),
    q('node-deployment-architecture', 'Deployment and Scalable Backend Architecture', 'Separate routes, services, data access, configuration, and deployment concerns as an API grows.', 'Advanced', ['Layers', 'Health checks', 'Deployment'], 'Plan an API structure', 'src/routes/\nsrc/services/\nsrc/repositories/\nsrc/config/\nsrc/app.ts', 'The structure gives each layer a clear responsibility and supports tests without requiring a live server.', ['The structure gives each layer a clear responsibility and supports tests without requiring a live server.', 'One file must own every concern.', 'Deployment removes the need for validation.'], 'Clear boundaries make backend changes easier to test and deploy.'),
    q('node-rest-capstone', 'Node.js REST API Capstone', 'Build a mini API with routes, validation, persistence, authentication concepts, and production checks.', 'Advanced', ['REST API', 'Validation', 'Reliability'], 'Build a lesson progress API', 'app.get("/progress", listProgress);\napp.post("/progress", validateProgress, createProgress);', 'The capstone exposes a documented API with consistent errors, bounded queries, tests, logs, and graceful shutdown notes.', ['The capstone exposes a documented API with consistent errors, bounded queries, tests, logs, and graceful shutdown notes.', 'A capstone only needs one route.', 'Security can be added after secrets leak.'], 'A backend capstone should prove the full request lifecycle and operational thinking.', ['node-validation', 'node-testing-logging']),
  ]}),
];
