import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';

const q = (id: string, title: string, summary: string, level: 'Beginner' | 'Intermediate' | 'Advanced', focus: string[], exercise: string, starterCode: string, answer: string, options: string[], explanation: string, prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus, exercise, starterCode, expectedResult: 'The example renders the intended state and remains understandable when the data changes.', challenge: 'Add an empty or error state and explain where that state belongs.', references: ['React documentation', 'Component design', ...focus], quizQuestion: `What is the main idea in ${title}?`, quizAnswer: answer, quizOptions: options, quizExplanation: explanation, prerequisites });

export const reactExpansionSections: TopicSection[] = [
  createSection({ id: 'react-ui-foundations', title: 'React UI Foundations', subtitle: 'Composition, forms, and predictable rendering', topics: [
    q('react-conditional-rendering', 'Conditional Rendering', 'Show useful UI for loading, empty, success, and error states.', 'Beginner', ['Ternaries', 'Early returns', 'State-driven UI'], 'Build a status panel', 'return loading ? <p>Loading</p> : <p>{message}</p>;', 'UI should be derived from current state.', ['UI should be derived from current state.', 'Every state needs a separate app.', 'Conditions belong only in CSS.'], 'React renders the branch that matches the current data.'),
    q('react-component-composition', 'Component Composition', 'Combine small components through children and focused boundaries.', 'Beginner', ['children', 'Composition', 'Single responsibility'], 'Build a reusable panel', 'function Panel({ children }) { return <section>{children}</section>; }', 'Composition lets a container own layout while callers provide content.', ['Composition lets a container own layout while callers provide content.', 'Composition means copying markup.', 'Children can only be text.'], 'Composition reduces rigid components and makes reuse more flexible.'),
    q('react-forms', 'Forms and User Input', 'Collect and validate input while keeping feedback close to the field.', 'Beginner', ['Form events', 'Validation', 'Submit handling'], 'Build a lesson search form', '<form onSubmit={handleSubmit}><input value={query} onChange={handleChange} /></form>', 'A form owns a clear submit path and explains invalid input.', ['A form owns a clear submit path and explains invalid input.', 'Forms should reload every time.', 'Input values never need validation.'], 'Explicit state and validation make form behavior predictable.', ['react-state-events']),
    q('react-derived-state', 'Derived State and State Shape', 'Avoid duplicate state by calculating values from the smallest source of truth.', 'Intermediate', ['Source of truth', 'Selectors', 'Immutable updates'], 'Build a filtered lesson count', 'const visible = lessons.filter((lesson) => lesson.level === level);', 'The view calculates filtered data without storing a second copy that can go stale.', ['The view calculates filtered data without storing a second copy that can go stale.', 'Every calculation must be state.', 'Derived state should be mutated directly.'], 'Less duplicated state means fewer synchronization bugs.', ['react-state-events']),
  ]}),
  createSection({ id: 'react-hooks-data', title: 'React Hooks and Data', subtitle: 'Effects, refs, context, reducers, and API states', topics: [
    q('react-useref', 'useRef and DOM References', 'Keep mutable values or element references without causing a render for every change.', 'Intermediate', ['Refs', 'Focus management', 'Mutable values'], 'Focus a search input', 'const inputRef = useRef(null);\ninputRef.current?.focus();', 'The ref points to the input and focus happens from an intentional action.', ['The ref points to the input and focus happens from an intentional action.', 'Refs replace all state.', 'Changing a ref always re-renders.'], 'Refs are useful for imperative escape hatches, not ordinary displayed state.', ['react-forms']),
    q('react-context', 'Context and Shared Values', 'Share stable app-wide values without threading the same prop through every layer.', 'Intermediate', ['Provider', 'Consumer', 'Scope'], 'Share a theme value', 'const ThemeContext = createContext("light");\n<ThemeContext.Provider value="dark">{children}</ThemeContext.Provider>', 'Context supplies a value to descendants that opt into it.', ['Context supplies a value to descendants that opt into it.', 'Context stores data on a server.', 'Context prevents all renders.'], 'Context is useful for cross-cutting values such as theme or locale.'),
    q('react-usereducer', 'useReducer for State Transitions', 'Model related state changes as named actions and one predictable reducer.', 'Intermediate', ['Actions', 'Reducer purity', 'Complex state'], 'Build a lesson progress reducer', 'function reducer(state, action) {\n  if (action.type === "complete") return { ...state, done: true };\n  return state;\n}', 'Actions describe what happened and the reducer returns the next state without mutation.', ['Actions describe what happened and the reducer returns the next state without mutation.', 'Reducers perform network calls.', 'Reducers mutate the old object.'], 'Reducers make multi-step state transitions easier to inspect and test.'),
    q('react-api-fetching', 'API Fetching and Loading States', 'Represent idle, loading, success, and failure states around a request.', 'Intermediate', ['Request state', 'Cancellation', 'Errors'], 'Build an offline-ready data loader', 'const [state, setState] = useState({ status: "idle", data: [] });', 'The UI communicates request progress and does not confuse an empty result with a failure.', ['The UI communicates request progress and does not confuse an empty result with a failure.', 'Requests need no error state.', 'Loading should block all feedback.'], 'Explicit request states prevent ambiguous interfaces.', ['react-effects', 'react-usereducer']),
  ]}),
  createSection({ id: 'react-architecture-quality', title: 'React Architecture and Quality', subtitle: 'Reusable systems, routing, accessibility, and testing', topics: [
    q('react-state-lifting', 'State Lifting and Shared Workflows', 'Move state to the nearest common owner when sibling components need the same value.', 'Intermediate', ['Ownership', 'Callbacks', 'Data flow'], 'Coordinate a filter and list', 'function Page() { const [filter, setFilter] = useState("all"); return <><Filter value={filter} onChange={setFilter} /><List filter={filter} /></>; }', 'One owner coordinates the filter while children stay focused on their role.', ['One owner coordinates the filter while children stay focused on their role.', 'All components need global state.', 'Children should mutate parent state directly.'], 'Lifting state creates one source of truth for a shared workflow.'),
    q('react-routing', 'Routing Concepts and Screen Boundaries', 'Organize URLs, route parameters, and layouts without coupling every component together.', 'Intermediate', ['Routes', 'Parameters', 'Layouts'], 'Plan a lesson route', 'Route: /languages/:languageKey/topics/:topicId', 'A route identifies the screen and passes only stable identifiers needed to resolve local data.', ['A route identifies the screen and passes only stable identifiers needed to resolve local data.', 'Routes should contain whole lesson objects.', 'Every screen needs one URL.'], 'Stable route identifiers keep navigation payloads small and durable.'),
    q('react-accessibility', 'Accessibility in React', 'Make interactive components usable with keyboard, labels, focus, and semantic elements.', 'Advanced', ['Labels', 'Keyboard flow', 'Focus'], 'Audit a form component', '<label htmlFor="email">Email</label>\n<input id="email" type="email" />', 'Controls have names, states are announced where needed, and keyboard users can complete the flow.', ['Controls have names, states are announced where needed, and keyboard users can complete the flow.', 'ARIA replaces semantic HTML.', 'Keyboard access is optional.'], 'Accessible structure is part of component correctness.'),
    q('react-testing', 'React Testing Strategies', 'Test user-visible behavior without coupling tests to implementation details.', 'Advanced', ['User behavior', 'Queries', 'Test boundaries'], 'Test a completion button', 'render(<LessonCard completed={false} onComplete={onComplete} />);\nfireEvent.click(screen.getByRole("button"));', 'The test proves the user can complete a lesson and the callback is called.', ['The test proves the user can complete a lesson and the callback is called.', 'Tests should inspect private variables.', 'Only snapshots can test React.'], 'Behavior-focused tests survive internal refactors better.'),
  ]}),
  createSection({ id: 'react-advanced-projects', title: 'React Advanced Projects', subtitle: 'Rendering, performance, resilience, and capstone planning', topics: [
    q('react-rendering-model', 'React Rendering Model', 'Understand render, commit, state updates, and why components render again.', 'Advanced', ['Render phase', 'Commit phase', 'State updates'], 'Trace a render', 'const [count, setCount] = useState(0);\nreturn <button onClick={() => setCount(count + 1)}>{count}</button>;', 'A state update schedules a render and React commits the resulting UI changes.', ['A state update schedules a render and React commits the resulting UI changes.', 'Render means the browser reloads.', 'Every render changes the DOM.'], 'React can render without changing every DOM node.'),
    q('react-memoization', 'Memoization and Performance', 'Use memo, useMemo, and useCallback only when a measured render cost justifies them.', 'Advanced', ['React.memo', 'useMemo', 'useCallback'], 'Measure a slow list', 'const visible = useMemo(() => filterLessons(lessons, query), [lessons, query]);', 'The optimization has a measured reason and stable dependencies.', ['The optimization has a measured reason and stable dependencies.', 'Memoization always improves performance.', 'useMemo is required for every value.'], 'Memoization has a cost and should solve a demonstrated problem.'),
    q('react-lazy-suspense', 'Lazy Loading and Suspense Concepts', 'Load infrequently used screens separately and show a clear fallback while waiting.', 'Advanced', ['lazy', 'Suspense', 'Fallbacks'], 'Split an admin screen', 'const Admin = lazy(() => import("./Admin"));\n<Suspense fallback={<p>Loading...</p>}><Admin /></Suspense>', 'The initial screen stays smaller and the user sees a useful loading fallback.', ['The initial screen stays smaller and the user sees a useful loading fallback.', 'Suspense is an API client.', 'Lazy loading removes the need for errors.'], 'Code splitting can reduce initial work when boundaries match real navigation.'),
    q('react-scalable-capstone', 'React Task Dashboard Capstone', 'Combine reusable components, reducer state, accessible forms, data states, and performance review.', 'Advanced', ['Architecture', 'State management', 'Review'], 'Build a task dashboard', 'function App() { return <Dashboard filters={filters} tasks={tasks} />; }', 'The dashboard supports filtering, empty/loading/error states, keyboard use, and a documented component structure.', ['The dashboard supports filtering, empty/loading/error states, keyboard use, and a documented component structure.', 'A capstone only needs a screenshot.', 'All state belongs in one huge component.'], 'A useful capstone demonstrates decisions across the whole React workflow.', ['react-testing', 'react-memoization']),
  ]}),
];
