import { TopicSection } from '../../types';
import { createCurriculumTopic, createSection } from '../../utils';
const q = (id: string, title: string, summary: string, level: 'Beginner'|'Intermediate'|'Advanced', prerequisites?: string[]) => createCurriculumTopic({ id, title, summary, level, duration: title.includes('Capstone') ? '3h' : '1h 35m', focus: ['Go design', 'Practical exercise', 'Explicit errors'], exercise: `Build a local ${title.toLowerCase()} example`, starterCode: 'package main\n\nfunc main() {\n    // implement the focused Go concept\n}', expectedResult: `The example demonstrates ${title.toLowerCase()} with a checked result.`, challenge: 'Add a boundary case and a focused test.', references: ['Go standard library', title], quizQuestion: `Why is ${title} useful?`, quizAnswer: 'It gives a clear Go pattern for the problem it addresses.', quizOptions: ['It gives a clear Go pattern for the problem it addresses.', 'It only changes terminal colors.', 'It makes every error disappear.'], quizExplanation: 'Good Go code makes data flow, errors, and ownership of work visible.', prerequisites });
export const goExpansionSections: TopicSection[] = [
 createSection({ id: 'go-intermediate', title: 'Go Intermediate', subtitle: 'Compose packages, errors, files, JSON, and HTTP', topics: [
  q('go-methods-interfaces', 'Methods and Interfaces', 'Attach behavior to types and depend on small capabilities.', 'Intermediate'), q('go-pointers-errors', 'Pointers and Error Values', 'Use pointers where mutation or absence is meaningful and return errors explicitly.', 'Intermediate'), q('go-defer-panic', 'defer, panic, and recover', 'Guarantee cleanup and understand when recovery is appropriate.', 'Intermediate'), q('go-modules-files', 'Modules, Packages, and File Handling', 'Organize reusable code and read or write local resources.', 'Intermediate'), q('go-json', 'JSON Encoding and Decoding', 'Map structured data to JSON with validation at boundaries.', 'Intermediate'), q('go-http-client-server', 'HTTP Client and Server', 'Build request handlers and clients using the standard library.', 'Intermediate'), q('go-context', 'Context Basics', 'Carry deadlines, cancellation, and request-scoped values deliberately.', 'Intermediate'),
 ]}),
 createSection({ id: 'go-concurrency', title: 'Go Concurrency', subtitle: 'Coordinate concurrent work safely', topics: [
  q('go-goroutines', 'Goroutines', 'Start concurrent functions while keeping ownership and lifecycle visible.', 'Advanced'), q('go-channels', 'Channels and Buffered Channels', 'Communicate values between goroutines with bounded or unbuffered flow.', 'Advanced', ['go-goroutines']), q('go-select', 'select and Channel Coordination', 'Wait on multiple communication or cancellation paths.', 'Advanced', ['go-channels']), q('go-mutex-waitgroup', 'Mutexes and WaitGroups', 'Protect shared state and wait for a known set of workers.', 'Advanced'), q('go-worker-pools', 'Worker Pools', 'Bound concurrency and distribute jobs through a controlled queue.', 'Advanced', ['go-channels']), q('go-cancellation', 'Context Cancellation and Graceful Shutdown', 'Stop work cooperatively when a request or process ends.', 'Advanced', ['go-context']), q('go-races', 'Race Conditions and Security Basics', 'Recognize unsafe shared state and validate service inputs.', 'Advanced'),
 ]}),
 createSection({ id: 'go-services', title: 'Go Applied Services', subtitle: 'Build, test, observe, and deploy services', topics: [
  q('go-rest-structure', 'REST API Structure', 'Separate handlers, services, data access, and response models.', 'Advanced'), q('go-database', 'Database Integration Concepts', 'Use context-aware data access and explicit transaction boundaries.', 'Advanced'), q('go-testing-table', 'Testing and Table-Driven Tests', 'Cover multiple cases with concise, maintainable tests.', 'Intermediate'), q('go-logging-config', 'Logging and Configuration', 'Make operational settings and structured diagnostic output explicit.', 'Advanced'), q('go-profiling', 'Profiling and Performance', 'Measure allocations and latency before optimizing.', 'Advanced'), q('go-build-deploy', 'Build and Deployment Concepts', 'Produce repeatable binaries and document deployment assumptions.', 'Advanced'), q('go-service-capstone', 'Concurrent Go REST Service Capstone', 'Build a tested service with packages, JSON, context cancellation, workers, and graceful shutdown.', 'Advanced', ['go-rest-structure', 'go-testing-table', 'go-cancellation']),
 ]}),
 createSection({ id: 'go-applied-practice', title: 'Go Applied Practice', subtitle: 'Reinforce service reliability', topics: [
  q('go-health-checks', 'Health Check and Readiness Exercise', 'Separate process health from dependency readiness in a local service.', 'Intermediate'),
 ]}),
];
